-- GENERATED by scripts/fetch-report-tables.ps1 - do not edit by hand.
-- Per-ENCOUNTER activity% from WCL Casts tables (activeTime / fight
-- duration), pooled across specs. The per-spec anchor in SpellProfiles
-- averages every boss together, so fights with forced downtime score
-- as bad play - this carries each boss's own expected activity so the
-- anchor can shift to match what the fight actually allows.
-- factor = this encounter's median / the median across all encounters.
-- Generated 2026-08-03 - VS / DR / MQD. Reference median: 99.2%.
local _, TP = ...

TP.ActivityProfiles = TP.ActivityProfiles or {}
TP.ActivityProfiles.reference = 99.2
TP.ActivityProfiles["Belo'ren, Child of Al'ar"] = { n = 295, p50 = 98.4, factor = 0.992 }
TP.ActivityProfiles["Chimaerus, the Undreamt God"] = { n = 303, p50 = 99, factor = 0.998 }
TP.ActivityProfiles["Crown of the Cosmos"] = { n = 317, p50 = 92.8, factor = 0.935 }
TP.ActivityProfiles["Fallen-King Salhadaar"] = { n = 315, p50 = 99.3, factor = 1.001 }
TP.ActivityProfiles["Imperator Averzian"] = { n = 319, p50 = 99.3, factor = 1.001 }
TP.ActivityProfiles["Lightblinded Vanguard"] = { n = 320, p50 = 99.5, factor = 1.003 }
TP.ActivityProfiles["Midnight Falls"] = { n = 298, p50 = 97.6, factor = 0.984 }
TP.ActivityProfiles["Vaelgor & Ezzorak"] = { n = 318, p50 = 99.4, factor = 1.002 }
TP.ActivityProfiles["Vorasius"] = { n = 320, p50 = 99.2, factor = 1 }
