-- GENERATED by scripts/fetch-report-tables.ps1 - do not edit by hand.
-- Per-ENCOUNTER activity% from WCL Casts tables (activeTime / fight
-- duration), pooled across specs. The per-spec anchor in SpellProfiles
-- averages every boss together, so fights with forced downtime score
-- as bad play - this carries each boss's own expected activity so the
-- anchor can shift to match what the fight actually allows.
-- factor = this encounter's median / the median across all encounters.
-- Generated 2026-10-03 - The Venomous Abyss. Reference median: 99.2%.
local _, TP = ...

TP.ActivityProfiles = TP.ActivityProfiles or {}
TP.ActivityProfiles.reference = 99.2
TP.ActivityProfiles["Entombed Sentinels"] = { n = 384, p50 = 98.5, factor = 0.993 }
TP.ActivityProfiles["Nek'zali the Soulcoiler"] = { n = 408, p50 = 99.4, factor = 1.002 }
TP.ActivityProfiles["Nymrissa Wavecaller"] = { n = 409, p50 = 99.4, factor = 1.002 }
TP.ActivityProfiles["Sszorak"] = { n = 439, p50 = 99.4, factor = 1.002 }
TP.ActivityProfiles["The Coiled Altar"] = { n = 367, p50 = 99.3, factor = 1.001 }
TP.ActivityProfiles["The Lost Explorers"] = { n = 407, p50 = 99.1, factor = 0.999 }
TP.ActivityProfiles["The Twin Fangs"] = { n = 403, p50 = 99.3, factor = 1.001 }
TP.ActivityProfiles["Ula'tek"] = { n = 409, p50 = 93.4, factor = 0.942 }
TP.ActivityProfiles["Vashnik the Malignant"] = { n = 408, p50 = 99.3, factor = 1.001 }
