-- GENERATED by scripts\fetch-report-tables.ps1 - do not edit by hand.
-- Per-encounter damage-taken ability profiles from WCL DamageTaken
-- tables. hitRate = fraction of sampled player-fights that took the
-- ability (LOW = avoidable, good players dodge it); tankOnly = only
-- tanks took it; share = fraction of all damage taken. Feeds
-- DeathCause: names why a player died (avoidable / tankbuster / chip).
-- Generated 2026-07-25 - VS / DR / MQD.
local _, TP = ...

TP.DAMAGE_PROFILES = TP.DAMAGE_PROFILES or {}
TP.DAMAGE_PROFILES.ids = TP.DAMAGE_PROFILES.ids or {}
local E = TP.DAMAGE_PROFILES
E["Belo'ren, Child of Al'ar"] = E["Belo'ren, Child of Al'ar"] or {}
E["Belo'ren, Child of Al'ar"]["Burning Heart"] = { hitRate = 0.99, tankOnly = false, share = 0.257, guid = 1264650, n = 200 }
E["Belo'ren, Child of Al'ar"]["Burning Rush"] = { hitRate = 0.04, tankOnly = false, share = 0.005, guid = 111400, n = 200 }
E["Belo'ren, Child of Al'ar"]["Death Drop"] = { hitRate = 0.135, tankOnly = false, share = 0.003, guid = 1241333, n = 200 }
E["Belo'ren, Child of Al'ar"]["Light Burn"] = { hitRate = 0.045, tankOnly = false, share = 0.002, guid = 1244348, n = 200 }
E["Belo'ren, Child of Al'ar"]["Light Dive"] = { hitRate = 0.23, tankOnly = false, share = 0.011, guid = 1241291, n = 200 }
E["Belo'ren, Child of Al'ar"]["Light Echo"] = { hitRate = 0.175, tankOnly = false, share = 0.019, guid = 1242991, n = 200 }
E["Belo'ren, Child of Al'ar"]["Light Edict"] = { hitRate = 0.03, tankOnly = true, share = 0.008, guid = 1241646, n = 200 }
E["Belo'ren, Child of Al'ar"]["Light Flames"] = { hitRate = 0.71, tankOnly = false, share = 0.205, guid = 1242803, n = 200 }
E["Belo'ren, Child of Al'ar"]["Light Quill"] = { hitRate = 0.075, tankOnly = false, share = 0.004, guid = 1242093, n = 200 }
E["Belo'ren, Child of Al'ar"]["Melee"] = { hitRate = 0.075, tankOnly = true, share = 0.024, guid = 1, n = 200 }
E["Belo'ren, Child of Al'ar"]["Void Burn"] = { hitRate = 0.065, tankOnly = false, share = 0.002, guid = 1266404, n = 200 }
E["Belo'ren, Child of Al'ar"]["Void Dive"] = { hitRate = 0.205, tankOnly = false, share = 0.01, guid = 1241340, n = 200 }
E["Belo'ren, Child of Al'ar"]["Void Echo"] = { hitRate = 0.25, tankOnly = false, share = 0.024, guid = 1242996, n = 200 }
E["Belo'ren, Child of Al'ar"]["Void Edict"] = { hitRate = 0.03, tankOnly = false, share = 0.01, guid = 1241676, n = 200 }
E["Belo'ren, Child of Al'ar"]["Void Flames"] = { hitRate = 0.65, tankOnly = false, share = 0.179, guid = 1242815, n = 200 }
E["Belo'ren, Child of Al'ar"]["Void Quill"] = { hitRate = 0.13, tankOnly = false, share = 0.008, guid = 1242094, n = 200 }
E["Belo'ren, Child of Al'ar"]["Voidlight Convergence"] = { hitRate = 0.95, tankOnly = false, share = 0.199, guid = 1241932, n = 200 }
E["Belo'ren, Child of Al'ar"]["Voidlight Rupture"] = { hitRate = 0.075, tankOnly = false, share = 0.014, guid = 1243866, n = 200 }
E.ids[3182] = "Belo'ren, Child of Al'ar"
E["Chimaerus, the Undreamt God"] = E["Chimaerus, the Undreamt God"] or {}
E["Chimaerus, the Undreamt God"]["Alndust Essence"] = { hitRate = 0.025, tankOnly = false, share = 0.002, guid = 1245919, n = 199 }
E["Chimaerus, the Undreamt God"]["Alndust Upheaval"] = { hitRate = 0.261, tankOnly = false, share = 0.051, guid = 1262305, n = 199 }
E["Chimaerus, the Undreamt God"]["Blessing of Dawn"] = { hitRate = 0.035, tankOnly = false, share = 0.004, guid = 210380, n = 199 }
E["Chimaerus, the Undreamt God"]["Caustic Phlegm"] = { hitRate = 0.98, tankOnly = false, share = 0.501, guid = 1246653, n = 199 }
E["Chimaerus, the Undreamt God"]["Colossal Strikes"] = { hitRate = 0.03, tankOnly = true, share = 0.004, guid = 1262053, n = 199 }
E["Chimaerus, the Undreamt God"]["Consume"] = { hitRate = 0.965, tankOnly = false, share = 0.211, guid = 1273112, n = 199 }
E["Chimaerus, the Undreamt God"]["Consuming Miasma"] = { hitRate = 0.161, tankOnly = false, share = 0.02, guid = 1257087, n = 199 }
E["Chimaerus, the Undreamt God"]["Discordant Roar"] = { hitRate = 0.075, tankOnly = false, share = 0.005, guid = 1249207, n = 199 }
E["Chimaerus, the Undreamt God"]["Dissonance"] = { hitRate = 0.216, tankOnly = false, share = 0.016, guid = 1267201, n = 199 }
E["Chimaerus, the Undreamt God"]["Fel Armor"] = { hitRate = 0.04, tankOnly = false, share = 0.001, guid = 387846, n = 199 }
E["Chimaerus, the Undreamt God"]["Lingering Miasma"] = { hitRate = 0.342, tankOnly = false, share = 0.035, guid = 1258192, n = 199 }
E["Chimaerus, the Undreamt God"]["Melee"] = { hitRate = 0.121, tankOnly = false, share = 0.054, guid = 1, n = 199 }
E["Chimaerus, the Undreamt God"]["Omnium Folio"] = { hitRate = 0.07, tankOnly = false, share = 0, guid = 1302265, n = 199 }
E["Chimaerus, the Undreamt God"]["Rift Emergence"] = { hitRate = 0.935, tankOnly = false, share = 0.08, guid = 1258610, n = 199 }
E["Chimaerus, the Undreamt God"]["Rift Madness"] = { hitRate = 0.045, tankOnly = false, share = 0.001, guid = 1275637, n = 199 }
E["Chimaerus, the Undreamt God"]["Shadow Word: Death"] = { hitRate = 0.03, tankOnly = false, share = 0.001, guid = 32409, n = 199 }
E["Chimaerus, the Undreamt God"]["Stagger"] = { hitRate = 0.025, tankOnly = true, share = 0.012, guid = 124255, n = 199 }
E["Chimaerus, the Undreamt God"]["Stretch Time"] = { hitRate = 0.03, tankOnly = false, share = 0.001, guid = 413924, n = 199 }
E.ids[3306] = "Chimaerus, the Undreamt God"
E["Crown of the Cosmos"] = E["Crown of the Cosmos"] or {}
E["Crown of the Cosmos"]["Cosmic Barrier"] = { hitRate = 0.79, tankOnly = false, share = 0.117, guid = 1261289, n = 200 }
E["Crown of the Cosmos"]["Echoing Darkness"] = { hitRate = 1, tankOnly = false, share = 0.191, guid = 1281707, n = 200 }
E["Crown of the Cosmos"]["Grasp of Emptiness"] = { hitRate = 0.175, tankOnly = false, share = 0.023, guid = 1260027, n = 200 }
E["Crown of the Cosmos"]["Gravity Collapse"] = { hitRate = 0.245, tankOnly = false, share = 0.031, guid = 1239095, n = 200 }
E["Crown of the Cosmos"]["Melee"] = { hitRate = 0.1, tankOnly = true, share = 0.084, guid = 1, n = 200 }
E["Crown of the Cosmos"]["Simulacrum Backlash"] = { hitRate = 0.9, tankOnly = false, share = 0.157, guid = 1260019, n = 200 }
E["Crown of the Cosmos"]["Void Expulsion"] = { hitRate = 0.68, tankOnly = false, share = 0.085, guid = 1233826, n = 200 }
E["Crown of the Cosmos"]["Voidstalker Sting"] = { hitRate = 0.95, tankOnly = false, share = 0.295, guid = 1237040, n = 200 }
E.ids[3181] = "Crown of the Cosmos"
E["Fallen-King Salhadaar"] = E["Fallen-King Salhadaar"] or {}
E["Fallen-King Salhadaar"]["Cosmic Breath"] = { hitRate = 0.034, tankOnly = false, share = 0.001, guid = 1236548, n = 203 }
E["Fallen-King Salhadaar"]["Dark Radiation"] = { hitRate = 0.985, tankOnly = false, share = 0.243, guid = 1285504, n = 203 }
E["Fallen-King Salhadaar"]["Despotic Command"] = { hitRate = 0.655, tankOnly = false, share = 0.038, guid = 1260835, n = 203 }
E["Fallen-King Salhadaar"]["Destabilizing Strikes"] = { hitRate = 0.099, tankOnly = true, share = 0.104, guid = 1284963, n = 203 }
E["Fallen-King Salhadaar"]["Entropic Unraveling"] = { hitRate = 0.931, tankOnly = false, share = 0.153, guid = 1254018, n = 203 }
E["Fallen-King Salhadaar"]["Melee"] = { hitRate = 0.113, tankOnly = false, share = 0.049, guid = 1, n = 203 }
E["Fallen-King Salhadaar"]["Shattering Twilight"] = { hitRate = 0.217, tankOnly = false, share = 0.011, guid = 1262989, n = 203 }
E["Fallen-King Salhadaar"]["Torturous Extract"] = { hitRate = 0.478, tankOnly = false, share = 0.035, guid = 1245592, n = 203 }
E["Fallen-King Salhadaar"]["Twilight Spikes"] = { hitRate = 0.118, tankOnly = false, share = 0.007, guid = 1251213, n = 203 }
E["Fallen-King Salhadaar"]["Twisting Obscurity"] = { hitRate = 0.985, tankOnly = false, share = 0.334, guid = 1250686, n = 203 }
E["Fallen-King Salhadaar"]["Umbral Beams"] = { hitRate = 0.044, tankOnly = false, share = 0.003, guid = 1260030, n = 203 }
E["Fallen-King Salhadaar"]["Void Exposure"] = { hitRate = 0.153, tankOnly = false, share = 0.009, guid = 1250828, n = 203 }
E["Fallen-King Salhadaar"]["Void Infusion"] = { hitRate = 0.069, tankOnly = false, share = 0.008, guid = 1245960, n = 203 }
E.ids[3179] = "Fallen-King Salhadaar"
E["Imperator Averzian"] = E["Imperator Averzian"] or {}
E["Imperator Averzian"]["Dark Barrage"] = { hitRate = 0.216, tankOnly = false, share = 0.002, guid = 1274846, n = 199 }
E["Imperator Averzian"]["Dark Upheaval"] = { hitRate = 1, tankOnly = false, share = 0.782, guid = 1259903, n = 199 }
E["Imperator Averzian"]["Fel Armor"] = { hitRate = 0.035, tankOnly = false, share = 0, guid = 387846, n = 199 }
E["Imperator Averzian"]["Lingering Darkness"] = { hitRate = 0.568, tankOnly = false, share = 0.046, guid = 1280075, n = 199 }
E["Imperator Averzian"]["Melee"] = { hitRate = 0.101, tankOnly = true, share = 0.074, guid = 1, n = 199 }
E["Imperator Averzian"]["Oblivion's Wrath"] = { hitRate = 0.206, tankOnly = false, share = 0.01, guid = 1260718, n = 199 }
E["Imperator Averzian"]["Omnium Folio"] = { hitRate = 0.106, tankOnly = false, share = 0, guid = 1302265, n = 199 }
E["Imperator Averzian"]["Shadow Word: Death"] = { hitRate = 0.05, tankOnly = false, share = 0.001, guid = 32409, n = 199 }
E["Imperator Averzian"]["Shadow's Advance"] = { hitRate = 0.045, tankOnly = false, share = 0.001, guid = 1253691, n = 199 }
E["Imperator Averzian"]["Stretch Time"] = { hitRate = 0.04, tankOnly = false, share = 0.001, guid = 413924, n = 199 }
E["Imperator Averzian"]["Umbral Collapse"] = { hitRate = 0.99, tankOnly = false, share = 0.062, guid = 1249262, n = 199 }
E["Imperator Averzian"]["Void Fall"] = { hitRate = 0.05, tankOnly = false, share = 0.002, guid = 1258883, n = 199 }
E["Imperator Averzian"]["Void Rupture"] = { hitRate = 0.101, tankOnly = false, share = 0.004, guid = 1261249, n = 199 }
E.ids[3176] = "Imperator Averzian"
E["Lightblinded Vanguard"] = E["Lightblinded Vanguard"] or {}
E["Lightblinded Vanguard"]["Avenger's Shield"] = { hitRate = 0.675, tankOnly = false, share = 0.057, guid = 1246502, n = 200 }
E["Lightblinded Vanguard"]["Divine Hammer"] = { hitRate = 0.105, tankOnly = false, share = 0.008, guid = 1249047, n = 200 }
E["Lightblinded Vanguard"]["Divine Storm"] = { hitRate = 0.225, tankOnly = false, share = 0.021, guid = 1246765, n = 200 }
E["Lightblinded Vanguard"]["Divine Toll"] = { hitRate = 0.025, tankOnly = false, share = 0.001, guid = 1248652, n = 200 }
E["Lightblinded Vanguard"]["Execution Sentence"] = { hitRate = 0.715, tankOnly = false, share = 0.042, guid = 1249024, n = 200 }
E["Lightblinded Vanguard"]["Exorcism"] = { hitRate = 0.075, tankOnly = true, share = 0.019, guid = 1246745, n = 200 }
E["Lightblinded Vanguard"]["Light Infusion"] = { hitRate = 1, tankOnly = false, share = 0.341, guid = 1258661, n = 200 }
E["Lightblinded Vanguard"]["Melee"] = { hitRate = 0.1, tankOnly = true, share = 0.073, guid = 1, n = 200 }
E["Lightblinded Vanguard"]["Sacred Toll"] = { hitRate = 0.935, tankOnly = false, share = 0.154, guid = 1246749, n = 200 }
E["Lightblinded Vanguard"]["Searing Radiance"] = { hitRate = 1, tankOnly = false, share = 0.266, guid = 1255739, n = 200 }
E["Lightblinded Vanguard"]["Shield of the Righteous"] = { hitRate = 0.035, tankOnly = true, share = 0.006, guid = 1251859, n = 200 }
E.ids[3180] = "Lightblinded Vanguard"
E["Midnight Falls"] = E["Midnight Falls"] or {}
E["Midnight Falls"]["Burning Rush"] = { hitRate = 0.063, tankOnly = false, share = 0.004, guid = 111400, n = 207 }
E["Midnight Falls"]["Core Harvest"] = { hitRate = 0.377, tankOnly = false, share = 0.01, guid = 1282425, n = 207 }
E["Midnight Falls"]["Criticality"] = { hitRate = 0.242, tankOnly = false, share = 0.007, guid = 1281178, n = 207 }
E["Midnight Falls"]["Dark Rune"] = { hitRate = 0.415, tankOnly = false, share = 0.013, guid = 1249594, n = 207 }
E["Midnight Falls"]["Dimming"] = { hitRate = 0.048, tankOnly = false, share = 0.001, guid = 1252975, n = 207 }
E["Midnight Falls"]["Disintegration"] = { hitRate = 0.768, tankOnly = false, share = 0.025, guid = 1251649, n = 207 }
E["Midnight Falls"]["Glimmering"] = { hitRate = 0.372, tankOnly = false, share = 0.07, guid = 1254398, n = 207 }
E["Midnight Falls"]["Heaven's Glaives"] = { hitRate = 0.029, tankOnly = false, share = 0.001, guid = 1254076, n = 207 }
E["Midnight Falls"]["Heaven's Lance"] = { hitRate = 0.097, tankOnly = true, share = 0.032, guid = 1253878, n = 207 }
E["Midnight Falls"]["Impaled"] = { hitRate = 0.097, tankOnly = true, share = 0.058, guid = 1253879, n = 207 }
E["Midnight Falls"]["Melee"] = { hitRate = 0.097, tankOnly = true, share = 0.045, guid = 1253873, n = 207 }
E["Midnight Falls"]["Overkill Current"] = { hitRate = 0.058, tankOnly = false, share = 0.002, guid = 1285827, n = 207 }
E["Midnight Falls"]["Resonance"] = { hitRate = 0.29, tankOnly = false, share = 0.009, guid = 1249582, n = 207 }
E["Midnight Falls"]["Shattered Sky"] = { hitRate = 0.952, tankOnly = false, share = 0.668, guid = 1249797, n = 207 }
E["Midnight Falls"]["Stagger"] = { hitRate = 0.029, tankOnly = true, share = 0.023, guid = 124255, n = 207 }
E["Midnight Falls"]["Starsplinter"] = { hitRate = 0.353, tankOnly = false, share = 0.012, guid = 1281473, n = 207 }
E["Midnight Falls"]["Thunderous Well"] = { hitRate = 0.348, tankOnly = false, share = 0.01, guid = 1254644, n = 207 }
E["Midnight Falls"]["Void Swarm"] = { hitRate = 0.058, tankOnly = false, share = 0.006, guid = 1273033, n = 207 }
E.ids[3183] = "Midnight Falls"
E["Vaelgor & Ezzorak"] = E["Vaelgor & Ezzorak"] or {}
E["Vaelgor & Ezzorak"]["Dread Breath"] = { hitRate = 0.025, tankOnly = false, share = 0.001, guid = 1255979, n = 200 }
E["Vaelgor & Ezzorak"]["Gloom"] = { hitRate = 0.185, tankOnly = false, share = 0.014, guid = 1245500, n = 200 }
E["Vaelgor & Ezzorak"]["Gloomtouched"] = { hitRate = 0.1, tankOnly = false, share = 0.01, guid = 1283712, n = 200 }
E["Vaelgor & Ezzorak"]["Melee"] = { hitRate = 0.12, tankOnly = false, share = 0.105, guid = 1, n = 200 }
E["Vaelgor & Ezzorak"]["Midnight Flames"] = { hitRate = 0.955, tankOnly = false, share = 0.181, guid = 1250071, n = 200 }
E["Vaelgor & Ezzorak"]["Midnight Manifestation"] = { hitRate = 0.93, tankOnly = false, share = 0.252, guid = 1259275, n = 200 }
E["Vaelgor & Ezzorak"]["Nullbeam"] = { hitRate = 0.03, tankOnly = true, share = 0.005, guid = 1283856, n = 200 }
E["Vaelgor & Ezzorak"]["Nullsnap"] = { hitRate = 0.055, tankOnly = false, share = 0.003, guid = 1244413, n = 200 }
E["Vaelgor & Ezzorak"]["Nullzone Implosion"] = { hitRate = 0.965, tankOnly = false, share = 0.161, guid = 1285954, n = 200 }
E["Vaelgor & Ezzorak"]["Vaelwing"] = { hitRate = 0.1, tankOnly = true, share = 0.052, guid = 1280434, n = 200 }
E["Vaelgor & Ezzorak"]["Void Howl"] = { hitRate = 0.65, tankOnly = false, share = 0.072, guid = 1245302, n = 200 }
E["Vaelgor & Ezzorak"]["Voidbolt"] = { hitRate = 0.74, tankOnly = false, share = 0.134, guid = 1245175, n = 200 }
E.ids[3178] = "Vaelgor & Ezzorak"
E["Vorasius"] = E["Vorasius"] or {}
E["Vorasius"]["Aftershock"] = { hitRate = 0.037, tankOnly = false, share = 0.004, guid = 1276812, n = 215 }
E["Vorasius"]["Blisterburst"] = { hitRate = 0.54, tankOnly = false, share = 0.085, guid = 1259186, n = 215 }
E["Vorasius"]["Dark Energy"] = { hitRate = 0.833, tankOnly = false, share = 0.159, guid = 1280101, n = 215 }
E["Vorasius"]["Dark Goo"] = { hitRate = 0.047, tankOnly = false, share = 0.015, guid = 1243270, n = 215 }
E["Vorasius"]["Melee"] = { hitRate = 0.107, tankOnly = false, share = 0.03, guid = 1, n = 215 }
E["Vorasius"]["Parasite Expulsion"] = { hitRate = 0.465, tankOnly = false, share = 0.071, guid = 1275558, n = 215 }
E["Vorasius"]["Primordial Power"] = { hitRate = 0.93, tankOnly = false, share = 0.331, guid = 1272950, n = 215 }
E["Vorasius"]["Primordial Roar"] = { hitRate = 0.047, tankOnly = false, share = 0.004, guid = 1260052, n = 215 }
E["Vorasius"]["Shadowclaw Slam"] = { hitRate = 0.926, tankOnly = false, share = 0.271, guid = 1241808, n = 215 }
E["Vorasius"]["Void Breath"] = { hitRate = 0.07, tankOnly = false, share = 0.027, guid = 1257607, n = 215 }
E.ids[3177] = "Vorasius"
