-- GENERATED by scripts\fetch-report-tables.ps1 - do not edit by hand.
-- Per-encounter damage-taken ability profiles from WCL DamageTaken
-- tables. hitRate = fraction of sampled player-fights that took the
-- ability (LOW = avoidable, good players dodge it); tankOnly = only
-- tanks took it; share = fraction of all damage taken; avgDmg = a
-- taker's typical damage from it (per-taker, not per-hit - the table
-- has no hit counts). Feeds DeathCause (why a player died) and mechanic
-- coaching (names + impact of the avoidable ability a player ate).
-- Generated 2026-10-03 - The Venomous Abyss.
local _, TP = ...

TP.DAMAGE_PROFILES = TP.DAMAGE_PROFILES or {}
TP.DAMAGE_PROFILES.ids = TP.DAMAGE_PROFILES.ids or {}
local E = TP.DAMAGE_PROFILES
E["Entombed Sentinels"] = E["Entombed Sentinels"] or {}
E["Entombed Sentinels"]["Blessing of Dawn"] = { hitRate = 0.013, tankOnly = false, share = 0.002, avgDmg = 2182966, guid = 210380, n = 397 }
E["Entombed Sentinels"]["Blighted Blood"] = { hitRate = 0.063, tankOnly = false, share = 0.005, avgDmg = 1328277, guid = 1284471, n = 397 }
E["Entombed Sentinels"]["Blood Venom"] = { hitRate = 0.154, tankOnly = false, share = 0.014, avgDmg = 1564322, guid = 1284210, n = 397 }
E["Entombed Sentinels"]["Bloodvenom Injection"] = { hitRate = 0.086, tankOnly = true, share = 0.042, avgDmg = 8578443, guid = 1310126, n = 397 }
E["Entombed Sentinels"]["Burning Rush"] = { hitRate = 0.015, tankOnly = false, share = 0.001, avgDmg = 1366643, guid = 111400, n = 397 }
E["Entombed Sentinels"]["Clinging Murk"] = { hitRate = 0.023, tankOnly = false, share = 0.001, avgDmg = 686185, guid = 1303097, n = 397 }
E["Entombed Sentinels"]["Contaminate"] = { hitRate = 0.907, tankOnly = false, share = 0.124, avgDmg = 2380241, guid = 1284258, n = 397 }
E["Entombed Sentinels"]["Cultivated Burst"] = { hitRate = 0.055, tankOnly = false, share = 0.006, avgDmg = 1792045, guid = 1284948, n = 397 }
E["Entombed Sentinels"]["Deadly Venom"] = { hitRate = 0.043, tankOnly = false, share = 0.006, avgDmg = 2312944, guid = 1297338, n = 397 }
E["Entombed Sentinels"]["Empowering Slam"] = { hitRate = 0.053, tankOnly = true, share = 0.01, avgDmg = 3453121, guid = 1284458, n = 397 }
E["Entombed Sentinels"]["Helical Toxins"] = { hitRate = 0.02, tankOnly = false, share = 0, avgDmg = 280960, guid = 1284813, n = 397 }
E["Entombed Sentinels"]["Living Venom"] = { hitRate = 0.123, tankOnly = false, share = 0.009, avgDmg = 1250401, guid = 1284209, n = 397 }
E["Entombed Sentinels"]["Mark of Acid"] = { hitRate = 0.965, tankOnly = false, share = 0.291, avgDmg = 5254453, guid = 1284500, n = 397 }
E["Entombed Sentinels"]["Mark of Blood"] = { hitRate = 0.962, tankOnly = false, share = 0.287, avgDmg = 5187866, guid = 1284506, n = 397 }
E["Entombed Sentinels"]["Melee"] = { hitRate = 0.086, tankOnly = true, share = 0.083, avgDmg = 16852635, guid = 1, n = 397 }
E["Entombed Sentinels"]["Noxious Blast"] = { hitRate = 0.06, tankOnly = false, share = 0.002, avgDmg = 640785, guid = 1284452, n = 397 }
E["Entombed Sentinels"]["Refraction"] = { hitRate = 0.078, tankOnly = false, share = 0.007, avgDmg = 1510303, guid = 1309786, n = 397 }
E["Entombed Sentinels"]["Stagger"] = { hitRate = 0.013, tankOnly = true, share = 0.01, avgDmg = 13844191, guid = 124255, n = 397 }
E["Entombed Sentinels"]["Toxic Droplets"] = { hitRate = 0.65, tankOnly = false, share = 0.065, avgDmg = 1737777, guid = 1284451, n = 397 }
E["Entombed Sentinels"]["Unstable Miasma"] = { hitRate = 0.531, tankOnly = false, share = 0.034, avgDmg = 1105651, guid = 1288282, n = 397 }
E.ids[3445] = "Entombed Sentinels"
E["Nek'zali the Soulcoiler"] = E["Nek'zali the Soulcoiler"] or {}
E["Nek'zali the Soulcoiler"]["Anguished Echoes"] = { hitRate = 0.049, tankOnly = false, share = 0.003, avgDmg = 636051, guid = 1294846, n = 425 }
E["Nek'zali the Soulcoiler"]["Corpse Blight"] = { hitRate = 0.969, tankOnly = false, share = 0.199, avgDmg = 2519940, guid = 1307939, n = 425 }
E["Nek'zali the Soulcoiler"]["Cremation"] = { hitRate = 0.421, tankOnly = false, share = 0.036, avgDmg = 1057763, guid = 1289875, n = 425 }
E["Nek'zali the Soulcoiler"]["Essence Rend"] = { hitRate = 0.054, tankOnly = false, share = 0.003, avgDmg = 780133, guid = 1287434, n = 425 }
E["Nek'zali the Soulcoiler"]["Hollowing Strikes"] = { hitRate = 0.08, tankOnly = true, share = 0.033, avgDmg = 5102126, guid = 1284109, n = 425 }
E["Nek'zali the Soulcoiler"]["Hungering Pyre"] = { hitRate = 0.035, tankOnly = false, share = 0.003, avgDmg = 901286, guid = 1289855, n = 425 }
E["Nek'zali the Soulcoiler"]["Latent Cultist"] = { hitRate = 0.332, tankOnly = false, share = 0.049, avgDmg = 1809244, guid = 1288554, n = 425 }
E["Nek'zali the Soulcoiler"]["Melee"] = { hitRate = 0.094, tankOnly = false, share = 0.038, avgDmg = 4921605, guid = 1, n = 425 }
E["Nek'zali the Soulcoiler"]["Possession Barrage"] = { hitRate = 0.951, tankOnly = false, share = 0.111, avgDmg = 1426534, guid = 1292034, n = 425 }
E["Nek'zali the Soulcoiler"]["Refraction"] = { hitRate = 0.087, tankOnly = false, share = 0.009, avgDmg = 1260225, guid = 1309786, n = 425 }
E["Nek'zali the Soulcoiler"]["Slithering Flame"] = { hitRate = 0.148, tankOnly = false, share = 0.012, avgDmg = 962679, guid = 1294933, n = 425 }
E["Nek'zali the Soulcoiler"]["Soul Transfer"] = { hitRate = 0.092, tankOnly = false, share = 0.009, avgDmg = 1200631, guid = 1295085, n = 425 }
E["Nek'zali the Soulcoiler"]["Soulcoil Rite"] = { hitRate = 1, tankOnly = false, share = 0.436, avgDmg = 5341771, guid = 1288772, n = 425 }
E["Nek'zali the Soulcoiler"]["Soulcoil Well"] = { hitRate = 0.012, tankOnly = false, share = 0.002, avgDmg = 1639824, guid = 1290390, n = 425 }
E["Nek'zali the Soulcoiler"]["Uncoiling"] = { hitRate = 0.435, tankOnly = false, share = 0.034, avgDmg = 954774, guid = 1292315, n = 425 }
E["Nek'zali the Soulcoiler"]["Vessel of Awakening"] = { hitRate = 0.181, tankOnly = false, share = 0.018, avgDmg = 1235580, guid = 1297630, n = 425 }
E.ids[3470] = "Nek'zali the Soulcoiler"
E["Nymrissa Wavecaller"] = E["Nymrissa Wavecaller"] or {}
E["Nymrissa Wavecaller"]["Abyssal Rain"] = { hitRate = 1, tankOnly = false, share = 0.628, avgDmg = 7282859, guid = 1260843, n = 421 }
E["Nymrissa Wavecaller"]["Blessing of Dawn"] = { hitRate = 0.012, tankOnly = false, share = 0.002, avgDmg = 1612071, guid = 210380, n = 421 }
E["Nymrissa Wavecaller"]["Blessing of Sacrifice"] = { hitRate = 0.012, tankOnly = false, share = 0, avgDmg = 449232, guid = 6940, n = 421 }
E["Nymrissa Wavecaller"]["Burning Rush"] = { hitRate = 0.055, tankOnly = false, share = 0.005, avgDmg = 1034209, guid = 111400, n = 421 }
E["Nymrissa Wavecaller"]["Chilling Frost"] = { hitRate = 0.42, tankOnly = false, share = 0.017, avgDmg = 461667, guid = 1313393, n = 421 }
E["Nymrissa Wavecaller"]["Fel Armor"] = { hitRate = 0.071, tankOnly = false, share = 0.002, avgDmg = 250951, guid = 387846, n = 421 }
E["Nymrissa Wavecaller"]["Frost Orb"] = { hitRate = 0.449, tankOnly = false, share = 0.063, avgDmg = 1633109, guid = 1313448, n = 421 }
E["Nymrissa Wavecaller"]["Iceblade Flurry"] = { hitRate = 0.076, tankOnly = false, share = 0.063, avgDmg = 9654540, guid = 1282945, n = 421 }
E["Nymrissa Wavecaller"]["Lingering Frost"] = { hitRate = 0.361, tankOnly = false, share = 0.003, avgDmg = 107556, guid = 1257654, n = 421 }
E["Nymrissa Wavecaller"]["Melee"] = { hitRate = 0.078, tankOnly = false, share = 0.024, avgDmg = 3612104, guid = 1, n = 421 }
E["Nymrissa Wavecaller"]["Omnium Folio"] = { hitRate = 0.052, tankOnly = false, share = 0, avgDmg = 14051, guid = 1302265, n = 421 }
E["Nymrissa Wavecaller"]["Pop!"] = { hitRate = 0.936, tankOnly = false, share = 0.054, avgDmg = 666247, guid = 1266340, n = 421 }
E["Nymrissa Wavecaller"]["Pulsing Tides"] = { hitRate = 0.216, tankOnly = false, share = 0.034, avgDmg = 1817607, guid = 1271380, n = 421 }
E["Nymrissa Wavecaller"]["Refraction"] = { hitRate = 0.124, tankOnly = false, share = 0.01, avgDmg = 956762, guid = 1309786, n = 421 }
E["Nymrissa Wavecaller"]["Seriously Sharp Seashell"] = { hitRate = 0.112, tankOnly = false, share = 0, avgDmg = 47942, guid = 1292299, n = 421 }
E["Nymrissa Wavecaller"]["Set Fire to the Pain"] = { hitRate = 0.019, tankOnly = false, share = 0, avgDmg = 244189, guid = 453286, n = 421 }
E["Nymrissa Wavecaller"]["Shadow Word: Death"] = { hitRate = 0.017, tankOnly = false, share = 0, avgDmg = 116279, guid = 32409, n = 421 }
E["Nymrissa Wavecaller"]["Shatter"] = { hitRate = 0.067, tankOnly = false, share = 0.016, avgDmg = 2788051, guid = 1313456, n = 421 }
E["Nymrissa Wavecaller"]["Stretch Time"] = { hitRate = 0.021, tankOnly = false, share = 0.001, avgDmg = 610380, guid = 413924, n = 421 }
E["Nymrissa Wavecaller"]["Swirling Whirlpools"] = { hitRate = 0.145, tankOnly = false, share = 0.008, avgDmg = 604327, guid = 1258677, n = 421 }
E["Nymrissa Wavecaller"]["Wild Bite"] = { hitRate = 0.204, tankOnly = false, share = 0.065, avgDmg = 3708051, guid = 1265425, n = 421 }
E.ids[3379] = "Nymrissa Wavecaller"
E["Sszorak"] = E["Sszorak"] or {}
E["Sszorak"]["Blessing of Dawn"] = { hitRate = 0.013, tankOnly = false, share = 0.001, avgDmg = 2016045, guid = 210380, n = 451 }
E["Sszorak"]["Melee"] = { hitRate = 0.078, tankOnly = false, share = 0.035, avgDmg = 8228564, guid = 1, n = 451 }
E["Sszorak"]["Mutilate"] = { hitRate = 0.763, tankOnly = false, share = 0.066, avgDmg = 1578620, guid = 1285999, n = 451 }
E["Sszorak"]["Mutilated Gash"] = { hitRate = 0.953, tankOnly = false, share = 0.315, avgDmg = 6028357, guid = 1285998, n = 451 }
E["Sszorak"]["Raging Crosswinds"] = { hitRate = 0.016, tankOnly = false, share = 0.001, avgDmg = 662378, guid = 1285616, n = 451 }
E["Sszorak"]["Ravage"] = { hitRate = 0.086, tankOnly = false, share = 0.012, avgDmg = 2504638, guid = 1277101, n = 451 }
E["Sszorak"]["Refraction"] = { hitRate = 0.082, tankOnly = false, share = 0.008, avgDmg = 1790076, guid = 1309786, n = 451 }
E["Sszorak"]["Tempest"] = { hitRate = 0.424, tankOnly = false, share = 0.049, avgDmg = 2107949, guid = 1287083, n = 451 }
E["Sszorak"]["Ula'tek's Presence"] = { hitRate = 1, tankOnly = false, share = 0.345, avgDmg = 6302312, guid = 1285965, n = 451 }
E["Sszorak"]["Venomous Surge"] = { hitRate = 0.494, tankOnly = false, share = 0.028, avgDmg = 1027294, guid = 1306120, n = 451 }
E["Sszorak"]["Viscous Cyst"] = { hitRate = 0.916, tankOnly = false, share = 0.134, avgDmg = 2679098, guid = 1287205, n = 451 }
E.ids[3420] = "Sszorak"
E["The Coiled Altar"] = E["The Coiled Altar"] or {}
E["The Coiled Altar"]["Axegrinder"] = { hitRate = 0.061, tankOnly = false, share = 0.004, avgDmg = 1280666, guid = 1285017, n = 377 }
E["The Coiled Altar"]["Burning Rush"] = { hitRate = 0.013, tankOnly = false, share = 0.001, avgDmg = 1819240, guid = 111400, n = 377 }
E["The Coiled Altar"]["Coalesced Venom"] = { hitRate = 0.984, tankOnly = false, share = 0.333, avgDmg = 7254627, guid = 1282408, n = 377 }
E["The Coiled Altar"]["Corrupted Toxin"] = { hitRate = 0.061, tankOnly = true, share = 0.018, avgDmg = 6152001, guid = 1298795, n = 377 }
E["The Coiled Altar"]["Dread Bolt"] = { hitRate = 0.045, tankOnly = true, share = 0.01, avgDmg = 4857809, guid = 1307184, n = 377 }
E["The Coiled Altar"]["Dreadful Presence"] = { hitRate = 0.881, tankOnly = false, share = 0.188, avgDmg = 4575282, guid = 1288635, n = 377 }
E["The Coiled Altar"]["Fangs of the Coiled Altar"] = { hitRate = 0.451, tankOnly = false, share = 0.014, avgDmg = 678144, guid = 1282512, n = 377 }
E["The Coiled Altar"]["Gravebound"] = { hitRate = 0.061, tankOnly = false, share = 0.021, avgDmg = 7472937, guid = 1308330, n = 377 }
E["The Coiled Altar"]["Guillotine"] = { hitRate = 0.016, tankOnly = false, share = 0.001, avgDmg = 1359460, guid = 1283594, n = 377 }
E["The Coiled Altar"]["Melee"] = { hitRate = 0.085, tankOnly = true, share = 0.048, avgDmg = 12050314, guid = 1, n = 377 }
E["The Coiled Altar"]["Refraction"] = { hitRate = 0.09, tankOnly = false, share = 0.01, avgDmg = 2306940, guid = 1309786, n = 377 }
E["The Coiled Altar"]["Retaliatory Malice"] = { hitRate = 0.029, tankOnly = false, share = 0.001, avgDmg = 882634, guid = 1308323, n = 377 }
E["The Coiled Altar"]["Soul Sever"] = { hitRate = 0.019, tankOnly = false, share = 0.002, avgDmg = 2101574, guid = 1312630, n = 377 }
E["The Coiled Altar"]["Spirit Erasure"] = { hitRate = 0.801, tankOnly = false, share = 0.117, avgDmg = 3133805, guid = 1287722, n = 377 }
E["The Coiled Altar"]["Venom Rupture"] = { hitRate = 0.955, tankOnly = false, share = 0.212, avgDmg = 4752816, guid = 1299838, n = 377 }
E["The Coiled Altar"]["Venomfang"] = { hitRate = 0.167, tankOnly = false, share = 0.007, avgDmg = 936260, guid = 1306906, n = 377 }
E["The Coiled Altar"]["Volatile Venom"] = { hitRate = 0.101, tankOnly = false, share = 0.006, avgDmg = 1374658, guid = 1282288, n = 377 }
E["The Coiled Altar"]["Widow's Kiss"] = { hitRate = 0.032, tankOnly = false, share = 0.001, avgDmg = 388410, guid = 1283623, n = 377 }
E.ids[3429] = "The Coiled Altar"
E["The Lost Explorers"] = E["The Lost Explorers"] or {}
E["The Lost Explorers"]["Aftershock"] = { hitRate = 0.034, tankOnly = false, share = 0.001, avgDmg = 200832, guid = 1310500, n = 437 }
E["The Lost Explorers"]["Blast Wave"] = { hitRate = 0.059, tankOnly = false, share = 0.009, avgDmg = 1854261, guid = 1305844, n = 437 }
E["The Lost Explorers"]["Blink Nova"] = { hitRate = 0.95, tankOnly = false, share = 0.108, avgDmg = 1433426, guid = 1294334, n = 437 }
E["The Lost Explorers"]["Burning Flames"] = { hitRate = 0.048, tankOnly = false, share = 0.003, avgDmg = 824120, guid = 1310667, n = 437 }
E["The Lost Explorers"]["Elemental Explosion"] = { hitRate = 0.14, tankOnly = false, share = 0.005, avgDmg = 468652, guid = 1295952, n = 437 }
E["The Lost Explorers"]["Evil Eyes"] = { hitRate = 0.059, tankOnly = false, share = 0.002, avgDmg = 487061, guid = 1292764, n = 437 }
E["The Lost Explorers"]["Falling"] = { hitRate = 0.023, tankOnly = false, share = 0, avgDmg = 107939, guid = 3, n = 437 }
E["The Lost Explorers"]["Fel Armor"] = { hitRate = 0.025, tankOnly = false, share = 0.001, avgDmg = 303183, guid = 387846, n = 437 }
E["The Lost Explorers"]["Final Ascension"] = { hitRate = 0.16, tankOnly = false, share = 0.014, avgDmg = 1089362, guid = 1292780, n = 437 }
E["The Lost Explorers"]["Malevolent Presence"] = { hitRate = 1, tankOnly = false, share = 0.479, avgDmg = 6029101, guid = 1295450, n = 437 }
E["The Lost Explorers"]["Melee"] = { hitRate = 0.082, tankOnly = false, share = 0.099, avgDmg = 15068941, guid = 1, n = 437 }
E["The Lost Explorers"]["Mighty Thud"] = { hitRate = 0.652, tankOnly = false, share = 0.046, avgDmg = 890148, guid = 1300237, n = 437 }
E["The Lost Explorers"]["Piercing Frost"] = { hitRate = 0.039, tankOnly = false, share = 0.003, avgDmg = 1043122, guid = 1310662, n = 437 }
E["The Lost Explorers"]["Refraction"] = { hitRate = 0.085, tankOnly = false, share = 0.007, avgDmg = 1003624, guid = 1309786, n = 437 }
E["The Lost Explorers"]["Relic Rupture"] = { hitRate = 0.16, tankOnly = false, share = 0.007, avgDmg = 585996, guid = 1310027, n = 437 }
E["The Lost Explorers"]["Seriously Sharp Seashell"] = { hitRate = 0.014, tankOnly = false, share = 0, avgDmg = 41790, guid = 1292299, n = 437 }
E["The Lost Explorers"]["Shadow Breath"] = { hitRate = 0.023, tankOnly = false, share = 0.002, avgDmg = 1284705, guid = 1308238, n = 437 }
E["The Lost Explorers"]["Shredding Shards"] = { hitRate = 0.076, tankOnly = true, share = 0.018, avgDmg = 3055517, guid = 1310616, n = 437 }
E["The Lost Explorers"]["Splinters"] = { hitRate = 0.789, tankOnly = false, share = 0.167, avgDmg = 2654719, guid = 1308853, n = 437 }
E["The Lost Explorers"]["Spreading Flames"] = { hitRate = 0.018, tankOnly = false, share = 0.001, avgDmg = 522811, guid = 1314061, n = 437 }
E["The Lost Explorers"]["Stagger"] = { hitRate = 0.011, tankOnly = true, share = 0.008, avgDmg = 9296747, guid = 124255, n = 437 }
E["The Lost Explorers"]["Stretch Time"] = { hitRate = 0.021, tankOnly = false, share = 0.002, avgDmg = 1039089, guid = 413924, n = 437 }
E["The Lost Explorers"]["Throw Junk"] = { hitRate = 0.245, tankOnly = false, share = 0.014, avgDmg = 706012, guid = 1291935, n = 437 }
E.ids[3497] = "The Lost Explorers"
E["The Twin Fangs"] = E["The Twin Fangs"] or {}
E["The Twin Fangs"]["Blessing of Dawn"] = { hitRate = 0.012, tankOnly = false, share = 0.001, avgDmg = 1638512, guid = 210380, n = 418 }
E["The Twin Fangs"]["Burning Rush"] = { hitRate = 0.014, tankOnly = false, share = 0.001, avgDmg = 2070264, guid = 111400, n = 418 }
E["The Twin Fangs"]["Caustic Deluge"] = { hitRate = 0.112, tankOnly = false, share = 0.019, avgDmg = 3943257, guid = 1289237, n = 418 }
E["The Twin Fangs"]["Caustic Globule"] = { hitRate = 0.39, tankOnly = false, share = 0.022, avgDmg = 1291129, guid = 1289201, n = 418 }
E["The Twin Fangs"]["Coiling Ichor"] = { hitRate = 0.844, tankOnly = false, share = 0.075, avgDmg = 2032756, guid = 1290878, n = 418 }
E["The Twin Fangs"]["Congealed Gore"] = { hitRate = 0.012, tankOnly = false, share = 0.001, avgDmg = 1542678, guid = 1292552, n = 418 }
E["The Twin Fangs"]["Deadly Venom"] = { hitRate = 0.043, tankOnly = false, share = 0.003, avgDmg = 1518055, guid = 1297338, n = 418 }
E["The Twin Fangs"]["Eternal Venom"] = { hitRate = 0.959, tankOnly = false, share = 0.27, avgDmg = 6448989, guid = 1290480, n = 418 }
E["The Twin Fangs"]["Melee"] = { hitRate = 0.086, tankOnly = false, share = 0.075, avgDmg = 19925550, guid = 1, n = 418 }
E["The Twin Fangs"]["Ravenous Feast"] = { hitRate = 0.452, tankOnly = false, share = 0.04, avgDmg = 2048024, guid = 1290662, n = 418 }
E["The Twin Fangs"]["Refraction"] = { hitRate = 0.069, tankOnly = false, share = 0.006, avgDmg = 2060437, guid = 1309786, n = 418 }
E["The Twin Fangs"]["Sanguine Storm"] = { hitRate = 0.019, tankOnly = false, share = 0.001, avgDmg = 993676, guid = 1306876, n = 418 }
E["The Twin Fangs"]["Stir the Depths"] = { hitRate = 0.782, tankOnly = false, share = 0.043, avgDmg = 1269545, guid = 1292806, n = 418 }
E["The Twin Fangs"]["Stone Breaker"] = { hitRate = 0.074, tankOnly = false, share = 0.009, avgDmg = 2867968, guid = 1289153, n = 418 }
E["The Twin Fangs"]["Stretch Time"] = { hitRate = 0.017, tankOnly = false, share = 0.001, avgDmg = 1904285, guid = 413924, n = 418 }
E["The Twin Fangs"]["Toxic Fumes"] = { hitRate = 1, tankOnly = false, share = 0.427, avgDmg = 9800639, guid = 1294976, n = 418 }
E["The Twin Fangs"]["Venomous Emergence"] = { hitRate = 0.022, tankOnly = false, share = 0, avgDmg = 89902, guid = 1308122, n = 418 }
E["The Twin Fangs"]["Vile Flood"] = { hitRate = 0.012, tankOnly = false, share = 0, avgDmg = 701032, guid = 1294605, n = 418 }
E.ids[3421] = "The Twin Fangs"
E["Ula'tek"] = E["Ula'tek"] or {}
E["Ula'tek"]["Acidic Expulsion"] = { hitRate = 0.257, tankOnly = false, share = 0.022, avgDmg = 2694700, guid = 1313531, n = 420 }
E["Ula'tek"]["Blight Vein"] = { hitRate = 0.245, tankOnly = false, share = 0.015, avgDmg = 1918570, guid = 1317955, n = 420 }
E["Ula'tek"]["Caustic Waves"] = { hitRate = 0.14, tankOnly = false, share = 0.013, avgDmg = 2833330, guid = 1292403, n = 420 }
E["Ula'tek"]["Deadly Venom"] = { hitRate = 0.031, tankOnly = false, share = 0.001, avgDmg = 876591, guid = 1297338, n = 420 }
E["Ula'tek"]["Malignant Shell"] = { hitRate = 0.343, tankOnly = false, share = 0.031, avgDmg = 2876491, guid = 1297213, n = 420 }
E["Ula'tek"]["Melee"] = { hitRate = 0.098, tankOnly = false, share = 0.049, avgDmg = 15975966, guid = 1, n = 420 }
E["Ula'tek"]["Mephitic Thrash"] = { hitRate = 0.119, tankOnly = false, share = 0.005, avgDmg = 1250926, guid = 1296301, n = 420 }
E["Ula'tek"]["Mother's Wrath"] = { hitRate = 0.064, tankOnly = true, share = 0.015, avgDmg = 7643745, guid = 1298369, n = 420 }
E["Ula'tek"]["Necrotic Vapors"] = { hitRate = 1, tankOnly = false, share = 0.526, avgDmg = 16717199, guid = 1286835, n = 420 }
E["Ula'tek"]["Poisonous Bite"] = { hitRate = 0.012, tankOnly = true, share = 0.002, avgDmg = 4791701, guid = 1287032, n = 420 }
E["Ula'tek"]["Putrid Membrane"] = { hitRate = 0.169, tankOnly = false, share = 0.02, avgDmg = 3692288, guid = 1308275, n = 420 }
E["Ula'tek"]["Rage of the Shackled"] = { hitRate = 0.821, tankOnly = false, share = 0.078, avgDmg = 3014949, guid = 1307367, n = 420 }
E["Ula'tek"]["Refraction"] = { hitRate = 0.1, tankOnly = false, share = 0.013, avgDmg = 4148065, guid = 1309786, n = 420 }
E["Ula'tek"]["Serpent's Bite"] = { hitRate = 0.136, tankOnly = false, share = 0.012, avgDmg = 2860968, guid = 1293146, n = 420 }
E["Ula'tek"]["Spectral Coils"] = { hitRate = 0.905, tankOnly = false, share = 0.086, avgDmg = 3034117, guid = 1287265, n = 420 }
E["Ula'tek"]["Stagger"] = { hitRate = 0.014, tankOnly = true, share = 0.007, avgDmg = 16164130, guid = 124255, n = 420 }
E["Ula'tek"]["Stone Venom"] = { hitRate = 0.076, tankOnly = true, share = 0.066, avgDmg = 27474917, guid = 1298418, n = 420 }
E["Ula'tek"]["Time Dilation"] = { hitRate = 0.012, tankOnly = false, share = 0.002, avgDmg = 4718727, guid = 361029, n = 420 }
E["Ula'tek"]["Volatile Purge"] = { hitRate = 0.343, tankOnly = false, share = 0.034, avgDmg = 3112559, guid = 1316357, n = 420 }
E.ids[3492] = "Ula'tek"
E["Vashnik the Malignant"] = E["Vashnik the Malignant"] or {}
E["Vashnik the Malignant"]["Burning Presence"] = { hitRate = 0.652, tankOnly = false, share = 0.111, avgDmg = 1844220, guid = 1305901, n = 431 }
E["Vashnik the Malignant"]["Catalytic Bile"] = { hitRate = 0.016, tankOnly = false, share = 0.001, avgDmg = 372543, guid = 1282616, n = 431 }
E["Vashnik the Malignant"]["Caustic Explosion"] = { hitRate = 0.872, tankOnly = false, share = 0.144, avgDmg = 1794432, guid = 1295209, n = 431 }
E["Vashnik the Malignant"]["Caustic Surge"] = { hitRate = 0.826, tankOnly = false, share = 0.114, avgDmg = 1501854, guid = 1285979, n = 431 }
E["Vashnik the Malignant"]["Deadly Venom"] = { hitRate = 0.016, tankOnly = false, share = 0.001, avgDmg = 449330, guid = 1297338, n = 431 }
E["Vashnik the Malignant"]["Dripping Fangs"] = { hitRate = 0.079, tankOnly = true, share = 0.05, avgDmg = 6916883, guid = 1280934, n = 431 }
E["Vashnik the Malignant"]["Exploding Infection"] = { hitRate = 0.037, tankOnly = false, share = 0.006, avgDmg = 1709072, guid = 1295173, n = 431 }
E["Vashnik the Malignant"]["Malignant Catalyst"] = { hitRate = 0.139, tankOnly = false, share = 0.014, avgDmg = 1115437, guid = 1282525, n = 431 }
E["Vashnik the Malignant"]["Melee"] = { hitRate = 0.079, tankOnly = true, share = 0.071, avgDmg = 9785300, guid = 1, n = 431 }
E["Vashnik the Malignant"]["Plague Froth"] = { hitRate = 0.754, tankOnly = false, share = 0.162, avgDmg = 2339968, guid = 1281925, n = 431 }
E["Vashnik the Malignant"]["Plague Wave"] = { hitRate = 0.362, tankOnly = false, share = 0.059, avgDmg = 1771170, guid = 1295798, n = 431 }
E["Vashnik the Malignant"]["Refraction"] = { hitRate = 0.049, tankOnly = false, share = 0.008, avgDmg = 1729681, guid = 1309786, n = 431 }
E["Vashnik the Malignant"]["Toxic Vapor"] = { hitRate = 0.998, tankOnly = false, share = 0.255, avgDmg = 2775979, guid = 1284561, n = 431 }
E.ids[3455] = "Vashnik the Malignant"
