-- Healer INTAKE COVERAGE baselines for FIVE-MAN content: { p25, p50, p75 } of
-- a healer's healing divided by the intake that was actually THEIRS TO HEAL -
-- damage taken (absorbs counted on both sides) less what the group healed
-- itself - times the healer count. 1.0 means they covered a fair share of the
-- damage nobody else picked up.
--
-- CALIBRATED FROM REAL CAPTURES, NOT CRAWLED FROM WARCRAFT LOGS, and that is a
-- deliberate reversal after two crawls failed (Josh 2026-08-01).
--
-- Scoring a five-man healer on HPS pays them for their group standing in
-- things: correlation +0.44 with group intake, healers medianing 87.9 in M+
-- against damagers' 12.3 in the same runs. Coverage fixes that MEASUREMENT.
-- What it could not fix was the REFERENCE:
--
--   raid-crawled anchors   p50 0.97  -> real players scored a median of 22
--   M+-crawled anchors     p50 1.04  -> a median of 19.5, 23% under ten
--
-- The M+ crawl is the instructive failure. Its ranked population spans just
-- 0.06 from p25 to p75 - an elite slice with almost no internal dispersion,
-- the same short-tail problem the dungeon damage curves have - while real
-- players span 0.41 to 1.00. Every real healer sits below its p25. No metric
-- survives a reference like that, and the reference was always the problem.
--
-- So these quartiles are the OBSERVED distribution of 175 real five-man
-- healer-fights. 50 means "an average healer in content people actually run",
-- not "an average healer who logs Mythic+ to Warcraft Logs". For casual
-- five-man content that is the more honest comparison, and it is the only one
-- that produced a usable number.
--
-- TWO CAVEATS THAT MATTER:
--  * This is a BOOTSTRAP. Measuring the fitted population back against these
--    anchors returns a median of 50 BY CONSTRUCTION - definitional, not
--    evidence. Only captures taken AFTER this was written can test it.
--  * The sample is one player's groups, so "average" means average-for-those
--    pugs until there is a broader one. Re-fit when there is.
--
-- POOLED, not per-spec, on purpose. Per-spec samples ran n=13-18 for five of
-- six specs and their quartiles swung from p50 0.346 to 0.858, which is noise
-- rather than spec identity - and unlike healer DAMAGE, where fistweaving is a
-- real kit difference, no mechanism should make one healer cover a different
-- share of the same intake. Absorbs already cancel on both sides.
--
-- THIS FILE MUST NOT BE REGENERATED BY A CRAWL. The v2.11.2 monthly refresh
-- did exactly that and it reached players: the tank-mitigation slice defaulted
-- -OutCoverageFile to this path, so a WCL crawl silently replaced the fitted
-- quartiles with { 0.909, 1.067, 1.278 }. The real median (0.782) then sat
-- BELOW the crawled p25, which is the same structural failure described above
-- - five-man healers fell 30-38 points and up to 30% of them scored under ten.
-- HEALER_COVERAGE_SOURCE below is what lets tests/validate.lua notice, since
-- no round trip against shipped data can: this table's correctness depends on
-- a population the shipped data does not contain.
local _, TP = ...

TP.HEALER_COVERAGE_UNIT = "healable-share-x-healers"

-- "captures" = fitted to real recorded fights. A crawl emits "wcl-crawl", and
-- tests/validate.lua fails on anything that is not "captures".
TP.HEALER_COVERAGE_SOURCE = "captures"

TP.HEALER_COVERAGE_ANCHORS = {
	-- p25 / p50 / p75 of 175 real five-man healer-fights, retail
	default = { 0.414, 0.782, 1.001 },
}
