-- Healer INTAKE COVERAGE baselines for FIVE-MAN content, Mists client: the
-- same metric as Data/HealerCoverage.lua (healing / the intake that was
-- theirs to heal, times healer count) with anchors fitted to MISTS captures.
--
-- WHY MISTS GETS ITS OWN QUARTILES instead of borrowing retail's: measured
-- 2026-08-27 with scripts/fit-healer-coverage.lua over both clients' real
-- SavedVariables, the populations genuinely differ -
--   retail  (n=240)  p25 0.410  p50 0.798  p75 1.001
--   mists   (n=99)   p25 0.757  p50 0.943  p75 1.108
-- MoP five-man groups self-heal far less, so the healer covers more of the
-- intake; on retail anchors nearly every MoP healer would sit above median
-- by construction. (The same retail re-fit reproducing the shipped
-- 0.414/0.782/1.001 is what validates the fit script itself.)
--
-- Until this file existed, Mists five-man healers were scored on HPS against
-- pooled RAID curves and then hit the low-demand floor on every clean pull -
-- which read as "pinned at exactly 75, most dungeons" (Josh 2026-08-27).
-- The Scarlet Halls run in Engine.lua's comment (healers scoring 0.0-90.0 on
-- consecutive pulls) is the same failure before the floor papered over it.
--
-- Loading this also activates Engine's healer-damage drop for Mists five-mans
-- (both gate on HEALER_COVERAGE_UNIT): healer damage becomes context instead
-- of 21% of the grade. That is the intended pairing - "never remove a metric
-- before its replacement is in place" - and the replacement is now in place.
--
-- Bootstrap caveats are the retail file's, unchanged: one player's groups,
-- median 50 by construction against its own fitting population, re-fit when
-- a broader sample exists (scripts/fit-healer-coverage.lua <SV path...>).
-- THIS FILE MUST NOT BE REGENERATED BY A CRAWL - see Data/HealerCoverage.lua
-- for the v2.11.2 incident; validate.lua fails on any source but "captures".
local _, TP = ...

TP.HEALER_COVERAGE_UNIT = "healable-share-x-healers"
TP.HEALER_COVERAGE_SOURCE = "captures"

TP.HEALER_COVERAGE_ANCHORS = {
	-- p25 / p50 / p75 of 99 real five-man healer-fights, Mists
	default = { 0.757, 0.943, 1.108 },
}
