-- GENERATED by scripts\fetch-killtimes.ps1 - do not edit by hand.
-- Kill-duration quantiles per encounter+bracket from WCL speed
-- rankings (seconds; p99 = fastest). Merged into TP.Percentiles.
local _, TP = ...

TP.Percentiles = TP.Percentiles or {}
TP.Percentiles.encounters = TP.Percentiles.encounters or {}
local E = TP.Percentiles.encounters

local function put(name, bracket, killTime)
	E[name] = E[name] or {}
	E[name][bracket] = E[name][bracket] or {}
	E[name][bracket].killTime = killTime
end

put("Fallen Protectors", "3x10", { n = 1000, curve = { { 99, 155.3 }, { 95, 171.9 }, { 90, 184.2 }, { 75, 202.3 }, { 50, 224.7 }, { 25, 245.8 }, { 10, 257.9 } }, avgSize = 10 })
put("Fallen Protectors", "3x25", { n = 422, curve = { { 99, 174.4 }, { 95, 189.2 }, { 90, 201.1 }, { 75, 221.7 }, { 50, 248.1 }, { 25, 276.7 }, { 10, 328.6 } }, avgSize = 24.8 })
put("Fallen Protectors", "4x10", { n = 846, curve = { { 99, 207 }, { 95, 242.6 }, { 90, 267.3 }, { 75, 309.8 }, { 50, 369.2 }, { 25, 432 }, { 10, 480.9 } }, avgSize = 10 })
put("Fallen Protectors", "4x25", { n = 574, curve = { { 99, 156.8 }, { 95, 210.2 }, { 90, 236.4 }, { 75, 278.2 }, { 50, 338.4 }, { 25, 388.4 }, { 10, 438.6 } }, avgSize = 24.9 })
put("Galakras", "3x10", { n = 1000, curve = { { 99, 381.7 }, { 95, 388.3 }, { 90, 393.9 }, { 75, 412 }, { 50, 429.5 }, { 25, 440.2 }, { 10, 447.7 } }, avgSize = 10 })
put("Galakras", "3x25", { n = 476, curve = { { 99, 391.9 }, { 95, 400.1 }, { 90, 413 }, { 75, 435.3 }, { 50, 449.6 }, { 25, 465.5 }, { 10, 511.5 } }, avgSize = 24.8 })
put("Galakras", "4x10", { n = 858, curve = { { 99, 393.2 }, { 95, 437.2 }, { 90, 451.9 }, { 75, 472 }, { 50, 522.1 }, { 25, 555.9 }, { 10, 596.3 } }, avgSize = 10 })
put("Galakras", "4x25", { n = 564, curve = { { 99, 374.6 }, { 95, 405 }, { 90, 446.2 }, { 75, 476.5 }, { 50, 530.7 }, { 25, 576.9 }, { 10, 607.5 } }, avgSize = 24.9 })
put("Garrosh Hellscream", "3x10", { n = 1000, curve = { { 99, 249 }, { 95, 262.9 }, { 90, 271.9 }, { 75, 304.8 }, { 50, 348.2 }, { 25, 426.6 }, { 10, 454.7 } }, avgSize = 10 })
put("Garrosh Hellscream", "3x25", { n = 545, curve = { { 99, 249.9 }, { 95, 262.5 }, { 90, 273 }, { 75, 300.5 }, { 50, 339.9 }, { 25, 432.5 }, { 10, 498.8 } }, avgSize = 24.9 })
put("Garrosh Hellscream", "4x10", { n = 75, curve = { { 99, 485.8 }, { 95, 491.6 }, { 90, 498 }, { 75, 516.9 }, { 50, 543.7 }, { 25, 564.4 }, { 10, 680.3 } }, avgSize = 10 })
put("Garrosh Hellscream", "4x25", { n = 84, curve = { { 99, 464.4 }, { 95, 482.8 }, { 90, 502.9 }, { 75, 557.1 }, { 50, 575.3 }, { 25, 710.6 }, { 10, 777.8 } }, avgSize = 25 })
put("General Nazgrim", "3x10", { n = 1000, curve = { { 99, 120.7 }, { 95, 135 }, { 90, 140.7 }, { 75, 156 }, { 50, 195.4 }, { 25, 231.8 }, { 10, 249 } }, avgSize = 10 })
put("General Nazgrim", "3x25", { n = 453, curve = { { 99, 135.7 }, { 95, 147.5 }, { 90, 155.6 }, { 75, 189 }, { 50, 233.3 }, { 25, 257.7 }, { 10, 285.1 } }, avgSize = 24.7 })
put("General Nazgrim", "4x10", { n = 776, curve = { { 99, 143.5 }, { 95, 161.6 }, { 90, 185.9 }, { 75, 244.3 }, { 50, 282.9 }, { 25, 348.2 }, { 10, 435.8 } }, avgSize = 10 })
put("General Nazgrim", "4x25", { n = 536, curve = { { 99, 132.9 }, { 95, 161.8 }, { 90, 191.7 }, { 75, 249 }, { 50, 301.5 }, { 25, 422.6 }, { 10, 472.5 } }, avgSize = 24.9 })
put("Immerseus", "3x10", { n = 1000, curve = { { 99, 245.2 }, { 95, 261.5 }, { 90, 274.1 }, { 75, 294.9 }, { 50, 313.6 }, { 25, 334.1 }, { 10, 351.9 } }, avgSize = 10 })
put("Immerseus", "3x25", { n = 317, curve = { { 99, 205.3 }, { 95, 220.7 }, { 90, 228.4 }, { 75, 236.5 }, { 50, 253.1 }, { 25, 273.9 }, { 10, 311.8 } }, avgSize = 24.6 })
put("Immerseus", "4x10", { n = 1000, curve = { { 99, 254.3 }, { 95, 280.8 }, { 90, 300.6 }, { 75, 335.8 }, { 50, 378.7 }, { 25, 415.6 }, { 10, 454.7 } }, avgSize = 10 })
put("Immerseus", "4x25", { n = 617, curve = { { 99, 192.4 }, { 95, 207.8 }, { 90, 213.2 }, { 75, 224.2 }, { 50, 252.8 }, { 25, 274 }, { 10, 307.6 } }, avgSize = 24.8 })
put("Iron Juggernaut", "3x10", { n = 1000, curve = { { 99, 165.6 }, { 95, 182.6 }, { 90, 189.9 }, { 75, 200.6 }, { 50, 214.4 }, { 25, 231.3 }, { 10, 242.6 } }, avgSize = 10 })
put("Iron Juggernaut", "3x25", { n = 514, curve = { { 99, 197.9 }, { 95, 211.2 }, { 90, 215.7 }, { 75, 225.2 }, { 50, 241.2 }, { 25, 261 }, { 10, 290.7 } }, avgSize = 24.8 })
put("Iron Juggernaut", "4x10", { n = 697, curve = { { 99, 170.6 }, { 95, 199.7 }, { 90, 222.4 }, { 75, 257.3 }, { 50, 287 }, { 25, 315.4 }, { 10, 373.7 } }, avgSize = 10 })
put("Iron Juggernaut", "4x25", { n = 515, curve = { { 99, 155 }, { 95, 194.7 }, { 90, 212.9 }, { 75, 250.5 }, { 50, 282.7 }, { 25, 313.9 }, { 10, 365.2 } }, avgSize = 25 })
put("Kor'kron Dark Shaman", "3x10", { n = 1000, curve = { { 99, 90.8 }, { 95, 104.7 }, { 90, 114 }, { 75, 129.7 }, { 50, 148.9 }, { 25, 170.2 }, { 10, 186.2 } }, avgSize = 10 })
put("Kor'kron Dark Shaman", "3x25", { n = 496, curve = { { 99, 124.2 }, { 95, 134.7 }, { 90, 144.6 }, { 75, 158.8 }, { 50, 186.8 }, { 25, 218.5 }, { 10, 255.1 } }, avgSize = 24.8 })
put("Kor'kron Dark Shaman", "4x10", { n = 553, curve = { { 99, 145.5 }, { 95, 165.7 }, { 90, 192.5 }, { 75, 242.6 }, { 50, 309.6 }, { 25, 369.1 }, { 10, 410.3 } }, avgSize = 10 })
put("Kor'kron Dark Shaman", "4x25", { n = 466, curve = { { 99, 127.1 }, { 95, 168.7 }, { 90, 217.6 }, { 75, 271.5 }, { 50, 322.4 }, { 25, 366.3 }, { 10, 396.7 } }, avgSize = 25 })
put("Malkorok", "3x10", { n = 1000, curve = { { 99, 117.6 }, { 95, 128.2 }, { 90, 133.8 }, { 75, 143.6 }, { 50, 156.1 }, { 25, 168 }, { 10, 178.1 } }, avgSize = 10 })
put("Malkorok", "3x25", { n = 569, curve = { { 99, 129.9 }, { 95, 136.5 }, { 90, 141.1 }, { 75, 150.7 }, { 50, 164 }, { 25, 183.5 }, { 10, 203.6 } }, avgSize = 24.8 })
put("Malkorok", "4x10", { n = 469, curve = { { 99, 179.8 }, { 95, 196.4 }, { 90, 205.2 }, { 75, 221.7 }, { 50, 246.1 }, { 25, 267.8 }, { 10, 287.4 } }, avgSize = 10 })
put("Malkorok", "4x25", { n = 387, curve = { { 99, 159.6 }, { 95, 185.2 }, { 90, 201.6 }, { 75, 230 }, { 50, 255.6 }, { 25, 279.1 }, { 10, 297.2 } }, avgSize = 25 })
put("Norushen", "3x10", { n = 1000, curve = { { 99, 207.2 }, { 95, 222.1 }, { 90, 229.9 }, { 75, 244.2 }, { 50, 259.1 }, { 25, 275.1 }, { 10, 287.6 } }, avgSize = 10 })
put("Norushen", "3x25", { n = 449, curve = { { 99, 216.5 }, { 95, 238.2 }, { 90, 244.2 }, { 75, 258.7 }, { 50, 281 }, { 25, 311.2 }, { 10, 351 } }, avgSize = 24.8 })
put("Norushen", "4x10", { n = 993, curve = { { 99, 219.3 }, { 95, 245.1 }, { 90, 255.9 }, { 75, 280.3 }, { 50, 318.6 }, { 25, 357.8 }, { 10, 385.1 } }, avgSize = 10 })
put("Norushen", "4x25", { n = 574, curve = { { 99, 208.9 }, { 95, 244.8 }, { 90, 262.3 }, { 75, 294.3 }, { 50, 330.3 }, { 25, 365 }, { 10, 389.8 } }, avgSize = 25 })
put("Paragons of the Klaxxi", "3x10", { n = 1000, curve = { { 99, 231.4 }, { 95, 254.3 }, { 90, 262.6 }, { 75, 287.5 }, { 50, 317.8 }, { 25, 343.7 }, { 10, 362.4 } }, avgSize = 10 })
put("Paragons of the Klaxxi", "3x25", { n = 572, curve = { { 99, 244.9 }, { 95, 257.1 }, { 90, 268.5 }, { 75, 298.2 }, { 50, 330.5 }, { 25, 375.8 }, { 10, 420.2 } }, avgSize = 24.8 })
put("Paragons of the Klaxxi", "4x10", { n = 138, curve = { { 99, 409.1 }, { 95, 447.6 }, { 90, 471.1 }, { 75, 492.4 }, { 50, 543.1 }, { 25, 581.2 }, { 10, 622.4 } }, avgSize = 10 })
put("Paragons of the Klaxxi", "4x25", { n = 142, curve = { { 99, 390 }, { 95, 444.8 }, { 90, 474.6 }, { 75, 554.7 }, { 50, 612 }, { 25, 650.8 }, { 10, 693.2 } }, avgSize = 25 })
put("Sha of Pride", "3x10", { n = 1000, curve = { { 99, 162.4 }, { 95, 177.5 }, { 90, 185.1 }, { 75, 199.2 }, { 50, 211.9 }, { 25, 226 }, { 10, 236 } }, avgSize = 10 })
put("Sha of Pride", "3x25", { n = 500, curve = { { 99, 165.1 }, { 95, 175.1 }, { 90, 181.1 }, { 75, 195.9 }, { 50, 214.8 }, { 25, 241.6 }, { 10, 281.5 } }, avgSize = 24.9 })
put("Sha of Pride", "4x10", { n = 883, curve = { { 99, 206.7 }, { 95, 234.3 }, { 90, 245.7 }, { 75, 276.3 }, { 50, 318.4 }, { 25, 359.2 }, { 10, 398.5 } }, avgSize = 10 })
put("Sha of Pride", "4x25", { n = 508, curve = { { 99, 166.8 }, { 95, 213.3 }, { 90, 232.9 }, { 75, 265.8 }, { 50, 313.7 }, { 25, 354.4 }, { 10, 391.7 } }, avgSize = 25 })
put("Siegecrafter Blackfuse", "3x10", { n = 1000, curve = { { 99, 88.7 }, { 95, 104.3 }, { 90, 113.6 }, { 75, 129.3 }, { 50, 146 }, { 25, 166.2 }, { 10, 179.3 } }, avgSize = 10 })
put("Siegecrafter Blackfuse", "3x25", { n = 576, curve = { { 99, 137 }, { 95, 149.6 }, { 90, 157.6 }, { 75, 176 }, { 50, 197.4 }, { 25, 223 }, { 10, 270.9 } }, avgSize = 24.8 })
put("Siegecrafter Blackfuse", "4x10", { n = 250, curve = { { 99, 137.1 }, { 95, 181.4 }, { 90, 196.1 }, { 75, 222.1 }, { 50, 255.8 }, { 25, 283.4 }, { 10, 315.9 } }, avgSize = 10 })
put("Siegecrafter Blackfuse", "4x25", { n = 238, curve = { { 99, 192.8 }, { 95, 239.9 }, { 90, 262.7 }, { 75, 302.6 }, { 50, 361.2 }, { 25, 400.9 }, { 10, 447.2 } }, avgSize = 25 })
put("Spoils of Pandaria", "3x10", { n = 1000, curve = { { 99, 260.4 }, { 95, 286.5 }, { 90, 298.3 }, { 75, 318.7 }, { 50, 347.2 }, { 25, 375.9 }, { 10, 394.5 } }, avgSize = 10 })
put("Spoils of Pandaria", "3x25", { n = 573, curve = { { 99, 255 }, { 95, 272 }, { 90, 279.4 }, { 75, 303 }, { 50, 336 }, { 25, 374.7 }, { 10, 423.7 } }, avgSize = 24.8 })
put("Spoils of Pandaria", "4x10", { n = 429, curve = { { 99, 349.4 }, { 95, 394.7 }, { 90, 411.3 }, { 75, 452.2 }, { 50, 486.8 }, { 25, 514.7 }, { 10, 528.3 } }, avgSize = 10 })
put("Spoils of Pandaria", "4x25", { n = 377, curve = { { 99, 305.2 }, { 95, 352.9 }, { 90, 390.3 }, { 75, 436.3 }, { 50, 486.2 }, { 25, 516.8 }, { 10, 527.8 } }, avgSize = 25 })
put("Thok the Bloodthirsty", "3x10", { n = 1000, curve = { { 99, 140.9 }, { 95, 153.3 }, { 90, 159.4 }, { 75, 174.3 }, { 50, 198.4 }, { 25, 224.7 }, { 10, 242 } }, avgSize = 10 })
put("Thok the Bloodthirsty", "3x25", { n = 567, curve = { { 99, 175.7 }, { 95, 186.6 }, { 90, 196.4 }, { 75, 218.2 }, { 50, 244.8 }, { 25, 277.1 }, { 10, 330.4 } }, avgSize = 24.8 })
put("Thok the Bloodthirsty", "4x10", { n = 376, curve = { { 99, 210.6 }, { 95, 235.8 }, { 90, 257.7 }, { 75, 287.8 }, { 50, 331.2 }, { 25, 388 }, { 10, 428.9 } }, avgSize = 10 })
put("Thok the Bloodthirsty", "4x25", { n = 339, curve = { { 99, 192.2 }, { 95, 241 }, { 90, 269.4 }, { 75, 304.7 }, { 50, 364.6 }, { 25, 422.9 }, { 10, 456.2 } }, avgSize = 25 })

TP.Percentiles.ids = TP.Percentiles.ids or {}
TP.Percentiles.ids[51598] = "Fallen Protectors"
TP.Percentiles.ids[51622] = "Galakras"
TP.Percentiles.ids[51623] = "Garrosh Hellscream"
TP.Percentiles.ids[51603] = "General Nazgrim"
TP.Percentiles.ids[51602] = "Immerseus"
TP.Percentiles.ids[51600] = "Iron Juggernaut"
TP.Percentiles.ids[51606] = "Kor'kron Dark Shaman"
TP.Percentiles.ids[51595] = "Malkorok"
TP.Percentiles.ids[51624] = "Norushen"
TP.Percentiles.ids[51593] = "Paragons of the Klaxxi"
TP.Percentiles.ids[51604] = "Sha of Pride"
TP.Percentiles.ids[51601] = "Siegecrafter Blackfuse"
TP.Percentiles.ids[51594] = "Spoils of Pandaria"
TP.Percentiles.ids[51599] = "Thok the Bloodthirsty"
