-- GENERATED by scripts\fetch-killtimes.ps1 - do not edit by hand.
-- Kill-duration quantiles per encounter+bracket from WCL speed
-- rankings (seconds; p99 = fastest). Merged into TP.Percentiles.
local _, TP = ...

TP.Percentiles = TP.Percentiles or {}
TP.Percentiles.encounters = TP.Percentiles.encounters or {}
local E = TP.Percentiles.encounters

local function put(name, bracket, killTime)
	E[name] = E[name] or {}
	E[name][bracket] = E[name][bracket] or {}
	E[name][bracket].killTime = killTime
end

put("Fallen Protectors", "3x10", { n = 1000, curve = { { 99, 152.2 }, { 95, 167 }, { 90, 177.6 }, { 75, 197.1 }, { 50, 216.7 }, { 25, 236.8 }, { 10, 251 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 97 } })
put("Fallen Protectors", "3x25", { n = 434, curve = { { 99, 168.8 }, { 95, 187.8 }, { 90, 199.3 }, { 75, 220.1 }, { 50, 245.7 }, { 25, 273.9 }, { 10, 323.8 } }, avgSize = 24.8, healers = { avg = 5, mode = 5, modePct = 74 } })
put("Fallen Protectors", "4x10", { n = 991, curve = { { 99, 194.7 }, { 95, 226.6 }, { 90, 249.2 }, { 75, 290.2 }, { 50, 351.2 }, { 25, 404.4 }, { 10, 465.8 } }, avgSize = 10, healers = { avg = 2.2, mode = 2, modePct = 75 } })
put("Fallen Protectors", "4x25", { n = 614, curve = { { 99, 139.5 }, { 95, 197.5 }, { 90, 216.8 }, { 75, 257.8 }, { 50, 304.3 }, { 25, 362.6 }, { 10, 425.5 } }, avgSize = 24.9, healers = { avg = 4.6, mode = 5, modePct = 55 } })
put("Galakras", "3x10", { n = 1000, curve = { { 99, 380.9 }, { 95, 386 }, { 90, 392 }, { 75, 407 }, { 50, 426.7 }, { 25, 436.4 }, { 10, 443.5 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 99 } })
put("Galakras", "3x25", { n = 485, curve = { { 99, 391.9 }, { 95, 399.1 }, { 90, 413 }, { 75, 435 }, { 50, 448.8 }, { 25, 464.3 }, { 10, 511.2 } }, avgSize = 24.8, healers = { avg = 4.9, mode = 5, modePct = 68 } })
put("Galakras", "4x10", { n = 1000, curve = { { 99, 391.6 }, { 95, 428.2 }, { 90, 444.6 }, { 75, 464.8 }, { 50, 513.8 }, { 25, 543 }, { 10, 583.7 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 98 } })
put("Galakras", "4x25", { n = 602, curve = { { 99, 368.8 }, { 95, 394 }, { 90, 424.5 }, { 75, 462.3 }, { 50, 500.6 }, { 25, 550 }, { 10, 589.8 } }, avgSize = 25, healers = { avg = 4.5, mode = 5, modePct = 53 } })
put("Garrosh Hellscream", "3x10", { n = 1000, curve = { { 99, 241.1 }, { 95, 257.3 }, { 90, 264.8 }, { 75, 290.3 }, { 50, 324.5 }, { 25, 367.8 }, { 10, 424.5 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 94 } })
put("Garrosh Hellscream", "3x25", { n = 574, curve = { { 99, 249.8 }, { 95, 257.5 }, { 90, 264.5 }, { 75, 287.7 }, { 50, 322.6 }, { 25, 412.8 }, { 10, 477.1 } }, avgSize = 24.8, healers = { avg = 4.5, mode = 5, modePct = 49 } })
put("Garrosh Hellscream", "4x10", { n = 137, curve = { { 99, 430.9 }, { 95, 471.9 }, { 90, 488.6 }, { 75, 512 }, { 50, 532.8 }, { 25, 556.9 }, { 10, 574.3 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 100 } })
put("Garrosh Hellscream", "4x25", { n = 126, curve = { { 99, 417.2 }, { 95, 457.9 }, { 90, 495.5 }, { 75, 539.3 }, { 50, 567 }, { 25, 710.5 }, { 10, 777.8 } }, avgSize = 25, healers = { avg = 4, mode = 4, modePct = 63 } })
put("General Nazgrim", "3x10", { n = 1000, curve = { { 99, 115.6 }, { 95, 131.7 }, { 90, 137.6 }, { 75, 149.6 }, { 50, 180.9 }, { 25, 220.4 }, { 10, 236.5 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 88 } })
put("General Nazgrim", "3x25", { n = 464, curve = { { 99, 133.8 }, { 95, 145.6 }, { 90, 153.4 }, { 75, 187.7 }, { 50, 231.7 }, { 25, 255.2 }, { 10, 285.1 } }, avgSize = 24.7, healers = { avg = 4.9, mode = 5, modePct = 70 } })
put("General Nazgrim", "4x10", { n = 937, curve = { { 99, 126.7 }, { 95, 149.1 }, { 90, 167.2 }, { 75, 220 }, { 50, 273.6 }, { 25, 319.3 }, { 10, 429.6 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 86 } })
put("General Nazgrim", "4x25", { n = 583, curve = { { 99, 117.2 }, { 95, 146.4 }, { 90, 168.2 }, { 75, 205.8 }, { 50, 280.5 }, { 25, 346.3 }, { 10, 454.2 } }, avgSize = 25, healers = { avg = 4.4, mode = 5, modePct = 47 } })
put("Immerseus", "3x10", { n = 1000, curve = { { 99, 243.7 }, { 95, 257.7 }, { 90, 269 }, { 75, 290.5 }, { 50, 309 }, { 25, 326.3 }, { 10, 340.8 } }, avgSize = 10, healers = { avg = 2.2, mode = 2, modePct = 75 } })
put("Immerseus", "3x25", { n = 326, curve = { { 99, 205.3 }, { 95, 217.6 }, { 90, 226.2 }, { 75, 234.5 }, { 50, 252 }, { 25, 272.3 }, { 10, 306.5 } }, avgSize = 24.6, healers = { avg = 5.2, mode = 5, modePct = 63 } })
put("Immerseus", "4x10", { n = 1000, curve = { { 99, 250 }, { 95, 264.6 }, { 90, 283.7 }, { 75, 314.3 }, { 50, 351.8 }, { 25, 389.5 }, { 10, 412.9 } }, avgSize = 10, healers = { avg = 2.6, mode = 3, modePct = 57 } })
put("Immerseus", "4x25", { n = 639, curve = { { 99, 166.3 }, { 95, 202.9 }, { 90, 206.8 }, { 75, 216.4 }, { 50, 235.4 }, { 25, 264.7 }, { 10, 291.6 } }, avgSize = 24.8, healers = { avg = 5.4, mode = 5, modePct = 51 } })
put("Iron Juggernaut", "3x10", { n = 1000, curve = { { 99, 159.1 }, { 95, 175.4 }, { 90, 183.3 }, { 75, 196 }, { 50, 208.1 }, { 25, 221.2 }, { 10, 232.3 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 97 } })
put("Iron Juggernaut", "3x25", { n = 523, curve = { { 99, 192.5 }, { 95, 207.7 }, { 90, 213.5 }, { 75, 224.3 }, { 50, 239.3 }, { 25, 258.6 }, { 10, 289.9 } }, avgSize = 24.8, healers = { avg = 4.9, mode = 5, modePct = 72 } })
put("Iron Juggernaut", "4x10", { n = 859, curve = { { 99, 156.5 }, { 95, 183.2 }, { 90, 203 }, { 75, 241.8 }, { 50, 273.9 }, { 25, 304.5 }, { 10, 331.9 } }, avgSize = 10, healers = { avg = 2.5, mode = 3, modePct = 55 } })
put("Iron Juggernaut", "4x25", { n = 577, curve = { { 99, 139.9 }, { 95, 184.3 }, { 90, 199.5 }, { 75, 229.8 }, { 50, 265 }, { 25, 293.5 }, { 10, 325.7 } }, avgSize = 25, healers = { avg = 5, mode = 5, modePct = 43 } })
put("Kor'kron Dark Shaman", "3x10", { n = 1000, curve = { { 99, 88.3 }, { 95, 101.7 }, { 90, 108.3 }, { 75, 124.2 }, { 50, 139.8 }, { 25, 158.6 }, { 10, 172.8 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 97 } })
put("Kor'kron Dark Shaman", "3x25", { n = 506, curve = { { 99, 120 }, { 95, 134.4 }, { 90, 143.2 }, { 75, 157 }, { 50, 181.4 }, { 25, 216.9 }, { 10, 250.5 } }, avgSize = 24.8, healers = { avg = 4.9, mode = 5, modePct = 63 } })
put("Kor'kron Dark Shaman", "4x10", { n = 706, curve = { { 99, 128.5 }, { 95, 158.8 }, { 90, 175.1 }, { 75, 222.5 }, { 50, 286.7 }, { 25, 354.3 }, { 10, 393.6 } }, avgSize = 10, healers = { avg = 2.3, mode = 2, modePct = 65 } })
put("Kor'kron Dark Shaman", "4x25", { n = 545, curve = { { 99, 111.9 }, { 95, 161.7 }, { 90, 194.3 }, { 75, 253.3 }, { 50, 297.9 }, { 25, 346.5 }, { 10, 383.2 } }, avgSize = 25, healers = { avg = 4.8, mode = 5, modePct = 50 } })
put("Malkorok", "3x10", { n = 1000, curve = { { 99, 112 }, { 95, 124.2 }, { 90, 129.5 }, { 75, 138.9 }, { 50, 149.7 }, { 25, 160.4 }, { 10, 168.7 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 96 } })
put("Malkorok", "3x25", { n = 579, curve = { { 99, 125 }, { 95, 134.1 }, { 90, 138.2 }, { 75, 146.9 }, { 50, 160 }, { 25, 181.1 }, { 10, 200.9 } }, avgSize = 24.8, healers = { avg = 4.9, mode = 5, modePct = 69 } })
put("Malkorok", "4x10", { n = 623, curve = { { 99, 163.4 }, { 95, 189.2 }, { 90, 196.9 }, { 75, 213.1 }, { 50, 238.6 }, { 25, 262.3 }, { 10, 282.8 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 93 } })
put("Malkorok", "4x25", { n = 467, curve = { { 99, 141.6 }, { 95, 182 }, { 90, 194.1 }, { 75, 216.9 }, { 50, 244.7 }, { 25, 267.4 }, { 10, 287 } }, avgSize = 25, healers = { avg = 4.8, mode = 5, modePct = 54 } })
put("Norushen", "3x10", { n = 1000, curve = { { 99, 206 }, { 95, 217.5 }, { 90, 226.9 }, { 75, 240.2 }, { 50, 254.8 }, { 25, 269.5 }, { 10, 281.3 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 94 } })
put("Norushen", "3x25", { n = 460, curve = { { 99, 220.5 }, { 95, 236.7 }, { 90, 243.4 }, { 75, 257.5 }, { 50, 280.1 }, { 25, 310.6 }, { 10, 347.5 } }, avgSize = 24.8, healers = { avg = 5.1, mode = 5, modePct = 68 } })
put("Norushen", "4x10", { n = 1000, curve = { { 99, 205.4 }, { 95, 226.7 }, { 90, 239 }, { 75, 263.1 }, { 50, 293.5 }, { 25, 326.4 }, { 10, 354.4 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 95 } })
put("Norushen", "4x25", { n = 608, curve = { { 99, 196.9 }, { 95, 229.5 }, { 90, 247.5 }, { 75, 273.9 }, { 50, 305.2 }, { 25, 344.4 }, { 10, 376.3 } }, avgSize = 24.9, healers = { avg = 4.7, mode = 5, modePct = 63 } })
put("Paragons of the Klaxxi", "3x10", { n = 1000, curve = { { 99, 224 }, { 95, 244.4 }, { 90, 256 }, { 75, 271.7 }, { 50, 301.1 }, { 25, 326.8 }, { 10, 340.6 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 95 } })
put("Paragons of the Klaxxi", "3x25", { n = 594, curve = { { 99, 233.9 }, { 95, 253.3 }, { 90, 262.1 }, { 75, 287 }, { 50, 316.3 }, { 25, 364 }, { 10, 410.8 } }, avgSize = 24.8, healers = { avg = 4.7, mode = 5, modePct = 57 } })
put("Paragons of the Klaxxi", "4x10", { n = 222, curve = { { 99, 348.6 }, { 95, 424 }, { 90, 447.6 }, { 75, 483.5 }, { 50, 526.3 }, { 25, 576.3 }, { 10, 607.4 } }, avgSize = 10, healers = { avg = 2.2, mode = 2, modePct = 78 } })
put("Paragons of the Klaxxi", "4x25", { n = 199, curve = { { 99, 375.4 }, { 95, 400.3 }, { 90, 473.9 }, { 75, 536.5 }, { 50, 591.9 }, { 25, 648.7 }, { 10, 688.6 } }, avgSize = 25, healers = { avg = 5, mode = 5, modePct = 58 } })
put("Sha of Pride", "3x10", { n = 1000, curve = { { 99, 155.6 }, { 95, 170.6 }, { 90, 179.1 }, { 75, 193.9 }, { 50, 207.4 }, { 25, 219.9 }, { 10, 230.8 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 91 } })
put("Sha of Pride", "3x25", { n = 511, curve = { { 99, 159.8 }, { 95, 171.8 }, { 90, 178 }, { 75, 193.4 }, { 50, 213.9 }, { 25, 238 }, { 10, 278 } }, avgSize = 24.8, healers = { avg = 5, mode = 5, modePct = 71 } })
put("Sha of Pride", "4x10", { n = 1000, curve = { { 99, 187.3 }, { 95, 215.7 }, { 90, 232 }, { 75, 255.4 }, { 50, 299 }, { 25, 341.1 }, { 10, 378.1 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 92 } })
put("Sha of Pride", "4x25", { n = 568, curve = { { 99, 164 }, { 95, 194.7 }, { 90, 220.9 }, { 75, 246.5 }, { 50, 288.3 }, { 25, 330.2 }, { 10, 373.4 } }, avgSize = 25, healers = { avg = 4.6, mode = 5, modePct = 57 } })
put("Siegecrafter Blackfuse", "3x10", { n = 1000, curve = { { 99, 85.7 }, { 95, 97.3 }, { 90, 104.7 }, { 75, 120 }, { 50, 136.2 }, { 25, 152.7 }, { 10, 164.3 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 90 } })
put("Siegecrafter Blackfuse", "3x25", { n = 597, curve = { { 99, 134.2 }, { 95, 144.4 }, { 90, 152.8 }, { 75, 169.9 }, { 50, 191.2 }, { 25, 216 }, { 10, 266.8 } }, avgSize = 24.8, healers = { avg = 4.7, mode = 5, modePct = 60 } })
put("Siegecrafter Blackfuse", "4x10", { n = 366, curve = { { 99, 144.3 }, { 95, 160.9 }, { 90, 182.9 }, { 75, 211.6 }, { 50, 245.7 }, { 25, 276.5 }, { 10, 311.6 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 86 } })
put("Siegecrafter Blackfuse", "4x25", { n = 345, curve = { { 99, 183 }, { 95, 221.7 }, { 90, 249.8 }, { 75, 289.9 }, { 50, 349.8 }, { 25, 395.3 }, { 10, 430.7 } }, avgSize = 25, healers = { avg = 4.2, mode = 4, modePct = 48 } })
put("Spoils of Pandaria", "3x10", { n = 1000, curve = { { 99, 254.2 }, { 95, 278 }, { 90, 288.8 }, { 75, 309.2 }, { 50, 334.4 }, { 25, 360.5 }, { 10, 376.4 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 100 } })
put("Spoils of Pandaria", "3x25", { n = 582, curve = { { 99, 255 }, { 95, 269.1 }, { 90, 275.6 }, { 75, 299.1 }, { 50, 328.5 }, { 25, 369.1 }, { 10, 419.4 } }, avgSize = 24.7, healers = { avg = 5, mode = 5, modePct = 59 } })
put("Spoils of Pandaria", "4x10", { n = 590, curve = { { 99, 341.5 }, { 95, 386.2 }, { 90, 404.2 }, { 75, 436.4 }, { 50, 477.4 }, { 25, 508.7 }, { 10, 526.5 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 100 } })
put("Spoils of Pandaria", "4x25", { n = 457, curve = { { 99, 248.3 }, { 95, 322.1 }, { 90, 368.5 }, { 75, 417.4 }, { 50, 466 }, { 25, 501.8 }, { 10, 519.2 } }, avgSize = 25, healers = { avg = 4.9, mode = 5, modePct = 47 } })
put("Thok the Bloodthirsty", "3x10", { n = 1000, curve = { { 99, 136.9 }, { 95, 147.1 }, { 90, 154.8 }, { 75, 166.4 }, { 50, 186 }, { 25, 208.3 }, { 10, 225.2 } }, avgSize = 10, healers = { avg = 2.1, mode = 2, modePct = 91 } })
put("Thok the Bloodthirsty", "3x25", { n = 581, curve = { { 99, 168.6 }, { 95, 180.3 }, { 90, 190.4 }, { 75, 207 }, { 50, 238.2 }, { 25, 271.6 }, { 10, 326.5 } }, avgSize = 24.8, healers = { avg = 5.2, mode = 5, modePct = 65 } })
put("Thok the Bloodthirsty", "4x10", { n = 535, curve = { { 99, 177.5 }, { 95, 218.5 }, { 90, 238.7 }, { 75, 268.9 }, { 50, 313.9 }, { 25, 381.4 }, { 10, 420.6 } }, avgSize = 10, healers = { avg = 2.5, mode = 3, modePct = 53 } })
put("Thok the Bloodthirsty", "4x25", { n = 431, curve = { { 99, 162.2 }, { 95, 234.8 }, { 90, 254.8 }, { 75, 286.7 }, { 50, 332 }, { 25, 394.3 }, { 10, 439.8 } }, avgSize = 25, healers = { avg = 5.5, mode = 6, modePct = 45 } })

TP.Percentiles.ids = TP.Percentiles.ids or {}
TP.Percentiles.ids[51598] = "Fallen Protectors"
TP.Percentiles.ids[51622] = "Galakras"
TP.Percentiles.ids[51623] = "Garrosh Hellscream"
TP.Percentiles.ids[51603] = "General Nazgrim"
TP.Percentiles.ids[51602] = "Immerseus"
TP.Percentiles.ids[51600] = "Iron Juggernaut"
TP.Percentiles.ids[51606] = "Kor'kron Dark Shaman"
TP.Percentiles.ids[51595] = "Malkorok"
TP.Percentiles.ids[51624] = "Norushen"
TP.Percentiles.ids[51593] = "Paragons of the Klaxxi"
TP.Percentiles.ids[51604] = "Sha of Pride"
TP.Percentiles.ids[51601] = "Siegecrafter Blackfuse"
TP.Percentiles.ids[51594] = "Spoils of Pandaria"
TP.Percentiles.ids[51599] = "Thok the Bloodthirsty"
