-- GENERATED by scripts\fetch-killtimes.ps1 - do not edit by hand.
-- Kill-duration quantiles per encounter+bracket from WCL speed
-- rankings (seconds; p99 = fastest). Merged into TP.Percentiles.
local _, TP = ...

TP.Percentiles = TP.Percentiles or {}
TP.Percentiles.encounters = TP.Percentiles.encounters or {}
local E = TP.Percentiles.encounters

local function put(name, bracket, killTime)
	E[name] = E[name] or {}
	E[name][bracket] = E[name][bracket] or {}
	E[name][bracket].killTime = killTime
end

put("Gate of the Setting Sun", "all", { n = 60, curve = { { 99, 274.8 }, { 95, 284.7 }, { 90, 290.6 }, { 75, 307.6 }, { 50, 371 }, { 25, 410.8 }, { 10, 470 } } })
