-- GENERATED by scripts\fetch-killtimes.ps1 - do not edit by hand.
-- Kill-duration quantiles per encounter+bracket from WCL speed
-- rankings (seconds; p99 = fastest). Merged into TP.Percentiles.
local _, TP = ...

TP.Percentiles = TP.Percentiles or {}
TP.Percentiles.encounters = TP.Percentiles.encounters or {}
local E = TP.Percentiles.encounters

local function put(name, bracket, killTime)
	E[name] = E[name] or {}
	E[name][bracket] = E[name][bracket] or {}
	E[name][bracket].killTime = killTime
end

put("Entombed Sentinels", "3", { n = 1000, curve = { { 99, 174.7 }, { 95, 183.7 }, { 90, 189.6 }, { 75, 197.4 }, { 50, 204.2 }, { 25, 208.9 }, { 10, 211.3 } }, avgSize = 23.4, healers = { avg = 3.4, mode = 4, modePct = 38 } })
put("Entombed Sentinels", "4", { n = 1000, curve = { { 99, 219.6 }, { 95, 228.4 }, { 90, 235.9 }, { 75, 247.3 }, { 50, 265.3 }, { 25, 271.8 }, { 10, 275 } }, avgSize = 21.7, healers = { avg = 3.4, mode = 4, modePct = 40 } })
put("Nek'zali the Soulcoiler", "3", { n = 1000, curve = { { 99, 143.1 }, { 95, 156.8 }, { 90, 163 }, { 75, 173.2 }, { 50, 183.5 }, { 25, 190.2 }, { 10, 192.9 } }, avgSize = 21.8, healers = { avg = 3.3, mode = 3, modePct = 33 } })
put("Nek'zali the Soulcoiler", "4", { n = 1000, curve = { { 99, 191.9 }, { 95, 206.9 }, { 90, 211.4 }, { 75, 217.8 }, { 50, 225.6 }, { 25, 232.4 }, { 10, 236.5 } }, avgSize = 24.3, healers = { avg = 3.8, mode = 4, modePct = 45 } })
put("Nymrissa Wavecaller", "3", { n = 1000, curve = { { 99, 128.6 }, { 95, 140.3 }, { 90, 147.1 }, { 75, 159.6 }, { 50, 173 }, { 25, 182 }, { 10, 186.2 } }, avgSize = 22.7, healers = { avg = 3.6, mode = 4, modePct = 33 } })
put("Nymrissa Wavecaller", "4", { n = 1000, curve = { { 99, 179.8 }, { 95, 194.4 }, { 90, 200.5 }, { 75, 211.5 }, { 50, 221.8 }, { 25, 232.5 }, { 10, 236.7 } }, avgSize = 23, healers = { avg = 3.8, mode = 4, modePct = 43 } })
put("Sszorak", "3", { n = 1000, curve = { { 99, 171.4 }, { 95, 190.7 }, { 90, 197.9 }, { 75, 206.4 }, { 50, 216.1 }, { 25, 222.4 }, { 10, 225.7 } }, avgSize = 20.8, healers = { avg = 3, mode = 2, modePct = 31 } })
put("Sszorak", "4", { n = 1000, curve = { { 99, 220.5 }, { 95, 236.9 }, { 90, 245.7 }, { 75, 253.5 }, { 50, 259.6 }, { 25, 264.1 }, { 10, 266.1 } }, avgSize = 21.5, healers = { avg = 3.5, mode = 4, modePct = 42 } })
put("The Coiled Altar", "3", { n = 1000, curve = { { 99, 174.7 }, { 95, 193.2 }, { 90, 199.3 }, { 75, 209.7 }, { 50, 219.1 }, { 25, 225.4 }, { 10, 228.9 } }, avgSize = 22, healers = { avg = 3.5, mode = 4, modePct = 40 } })
put("The Coiled Altar", "4", { n = 1000, curve = { { 99, 277.5 }, { 95, 295.5 }, { 90, 302.5 }, { 75, 314.4 }, { 50, 325.9 }, { 25, 334.5 }, { 10, 338.8 } }, avgSize = 24.2, healers = { avg = 4.1, mode = 4, modePct = 52 } })
put("The Lost Explorers", "3", { n = 1000, curve = { { 99, 125.8 }, { 95, 133.5 }, { 90, 136.9 }, { 75, 142.5 }, { 50, 148.7 }, { 25, 153.2 }, { 10, 155.8 } }, avgSize = 23.8, healers = { avg = 3.6, mode = 4, modePct = 40 } })
put("The Lost Explorers", "4", { n = 1000, curve = { { 99, 161.7 }, { 95, 182 }, { 90, 190.6 }, { 75, 202 }, { 50, 211.1 }, { 25, 218.9 }, { 10, 222.2 } }, avgSize = 24.2, healers = { avg = 3.9, mode = 4, modePct = 41 } })
put("The Twin Fangs", "3", { n = 1000, curve = { { 99, 209.5 }, { 95, 224 }, { 90, 232.3 }, { 75, 244 }, { 50, 254.6 }, { 25, 261.2 }, { 10, 264.9 } }, avgSize = 23.4, healers = { avg = 3.5, mode = 4, modePct = 36 } })
put("The Twin Fangs", "4", { n = 1000, curve = { { 99, 276.7 }, { 95, 298.7 }, { 90, 307.9 }, { 75, 329.2 }, { 50, 344 }, { 25, 352.3 }, { 10, 355.7 } }, avgSize = 23.6, healers = { avg = 3.9, mode = 4, modePct = 45 } })
put("Ula'tek", "3", { n = 1000, curve = { { 99, 145.4 }, { 95, 147.5 }, { 90, 149 }, { 75, 151.3 }, { 50, 154.2 }, { 25, 156.4 }, { 10, 254.2 } }, avgSize = 24.5, healers = { avg = 3.9, mode = 4, modePct = 43 } })
put("Ula'tek", "4", { n = 1000, curve = { { 99, 433.7 }, { 95, 441 }, { 90, 444.7 }, { 75, 452.7 }, { 50, 466.6 }, { 25, 479.4 }, { 10, 494.1 } }, avgSize = 24.9, healers = { avg = 4.5, mode = 4, modePct = 52 } })
put("Vashnik the Malignant", "3", { n = 1000, curve = { { 99, 135.6 }, { 95, 142.8 }, { 90, 146 }, { 75, 152.3 }, { 50, 158.6 }, { 25, 163 }, { 10, 165.5 } }, avgSize = 24, healers = { avg = 3.6, mode = 4, modePct = 38 } })
put("Vashnik the Malignant", "4", { n = 1000, curve = { { 99, 204.4 }, { 95, 219.4 }, { 90, 225.5 }, { 75, 234.5 }, { 50, 243 }, { 25, 248.7 }, { 10, 251.2 } }, avgSize = 23.9, healers = { avg = 3.7, mode = 4, modePct = 45 } })

TP.Percentiles.ids = TP.Percentiles.ids or {}
TP.Percentiles.ids[3445] = "Entombed Sentinels"
TP.Percentiles.ids[3470] = "Nek'zali the Soulcoiler"
TP.Percentiles.ids[3379] = "Nymrissa Wavecaller"
TP.Percentiles.ids[3420] = "Sszorak"
TP.Percentiles.ids[3429] = "The Coiled Altar"
TP.Percentiles.ids[3497] = "The Lost Explorers"
TP.Percentiles.ids[3421] = "The Twin Fangs"
TP.Percentiles.ids[3492] = "Ula'tek"
TP.Percentiles.ids[3455] = "Vashnik the Malignant"
