-- GENERATED by scripts\fetch-killtimes.ps1 - do not edit by hand.
-- Kill-duration quantiles per encounter+bracket from WCL speed
-- rankings (seconds; p99 = fastest). Merged into TP.Percentiles.
local _, TP = ...

TP.Percentiles = TP.Percentiles or {}
TP.Percentiles.encounters = TP.Percentiles.encounters or {}
local E = TP.Percentiles.encounters

local function put(name, bracket, killTime)
	E[name] = E[name] or {}
	E[name][bracket] = E[name][bracket] or {}
	E[name][bracket].killTime = killTime
end

put("Fallen Protectors", "3x10", { n = 1000, curve = { { 99, 146.9 }, { 95, 163.3 }, { 90, 173.4 }, { 75, 192.3 }, { 50, 210.8 }, { 25, 229.7 }, { 10, 242.8 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 97 } })
put("Fallen Protectors", "3x25", { n = 446, curve = { { 99, 168 }, { 95, 186.5 }, { 90, 196.4 }, { 75, 219 }, { 50, 243 }, { 25, 270.1 }, { 10, 313.9 } }, avgSize = 24.8, healers = { avg = 5, mode = 5, modePct = 72 } })
put("Fallen Protectors", "4x10", { n = 1000, curve = { { 99, 157.1 }, { 95, 202.2 }, { 90, 223.4 }, { 75, 260.6 }, { 50, 308.9 }, { 25, 357.8 }, { 10, 389 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 83 } })
put("Fallen Protectors", "4x25", { n = 659, curve = { { 99, 134.1 }, { 95, 183.2 }, { 90, 200.7 }, { 75, 241.2 }, { 50, 280.4 }, { 25, 333.6 }, { 10, 401.9 } }, avgSize = 24.9, healers = { avg = 4.4, mode = 5, modePct = 51 } })
put("Galakras", "3x10", { n = 1000, curve = { { 99, 378.2 }, { 95, 384 }, { 90, 389.9 }, { 75, 402.2 }, { 50, 424.1 }, { 25, 433.8 }, { 10, 439.3 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 99 } })
put("Galakras", "3x25", { n = 498, curve = { { 99, 391.1 }, { 95, 398.7 }, { 90, 412.4 }, { 75, 433.4 }, { 50, 447.5 }, { 25, 463.3 }, { 10, 511.1 } }, avgSize = 24.7, healers = { avg = 4.9, mode = 5, modePct = 67 } })
put("Galakras", "4x10", { n = 1000, curve = { { 99, 382.3 }, { 95, 401.4 }, { 90, 427.6 }, { 75, 448.8 }, { 50, 471.6 }, { 25, 519.9 }, { 10, 536.4 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 97 } })
put("Galakras", "4x25", { n = 645, curve = { { 99, 360.1 }, { 95, 387 }, { 90, 402.1 }, { 75, 444.7 }, { 50, 475.2 }, { 25, 531.9 }, { 10, 572.9 } }, avgSize = 25, healers = { avg = 4.4, mode = 5, modePct = 45 } })
put("Garrosh Hellscream", "3x10", { n = 1000, curve = { { 99, 234.9 }, { 95, 251.7 }, { 90, 260 }, { 75, 276.1 }, { 50, 304.4 }, { 25, 334.7 }, { 10, 361.9 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 91 } })
put("Garrosh Hellscream", "3x25", { n = 610, curve = { { 99, 246.9 }, { 95, 254.7 }, { 90, 260.2 }, { 75, 277.8 }, { 50, 309 }, { 25, 391.6 }, { 10, 466.5 } }, avgSize = 24.8, healers = { avg = 4.4, mode = 4, modePct = 49 } })
put("Garrosh Hellscream", "4x10", { n = 220, curve = { { 99, 414.8 }, { 95, 458 }, { 90, 471.9 }, { 75, 499.5 }, { 50, 522.7 }, { 25, 549.5 }, { 10, 569.7 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 99 } })
put("Garrosh Hellscream", "4x25", { n = 194, curve = { { 99, 431.2 }, { 95, 467.1 }, { 90, 489.1 }, { 75, 524.1 }, { 50, 556 }, { 25, 671.6 }, { 10, 745.4 } }, avgSize = 25, healers = { avg = 3.9, mode = 4, modePct = 63 } })
put("General Nazgrim", "3x10", { n = 1000, curve = { { 99, 111 }, { 95, 128.8 }, { 90, 134.5 }, { 75, 146.4 }, { 50, 168.4 }, { 25, 205 }, { 10, 225.8 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 90 } })
put("General Nazgrim", "3x25", { n = 475, curve = { { 99, 132 }, { 95, 144.7 }, { 90, 152.1 }, { 75, 184.4 }, { 50, 229.9 }, { 25, 250.8 }, { 10, 281.6 } }, avgSize = 24.6, healers = { avg = 4.8, mode = 5, modePct = 67 } })
put("General Nazgrim", "4x10", { n = 1000, curve = { { 99, 104.6 }, { 95, 131.8 }, { 90, 144 }, { 75, 183.5 }, { 50, 246.3 }, { 25, 282 }, { 10, 322.7 } }, avgSize = 10, healers = { avg = 1.7, mode = 2, modePct = 71 } })
put("General Nazgrim", "4x25", { n = 635, curve = { { 99, 114 }, { 95, 136.6 }, { 90, 153.5 }, { 75, 187.2 }, { 50, 244.2 }, { 25, 295.5 }, { 10, 429.2 } }, avgSize = 25, healers = { avg = 4.1, mode = 5, modePct = 41 } })
put("Immerseus", "3x10", { n = 1000, curve = { { 99, 239.2 }, { 95, 251.3 }, { 90, 264.9 }, { 75, 284.3 }, { 50, 303.3 }, { 25, 319.4 }, { 10, 333 } }, avgSize = 10, healers = { avg = 2.2, mode = 2, modePct = 79 } })
put("Immerseus", "3x25", { n = 339, curve = { { 99, 205.3 }, { 95, 217.5 }, { 90, 225.5 }, { 75, 233.5 }, { 50, 250.8 }, { 25, 269.1 }, { 10, 311.8 } }, avgSize = 24.5, healers = { avg = 5.2, mode = 5, modePct = 64 } })
put("Immerseus", "4x10", { n = 1000, curve = { { 99, 243.7 }, { 95, 254.4 }, { 90, 266.3 }, { 75, 293.8 }, { 50, 325.1 }, { 25, 360 }, { 10, 383.6 } }, avgSize = 10, healers = { avg = 2.4, mode = 2, modePct = 58 } })
put("Immerseus", "4x25", { n = 684, curve = { { 99, 180.3 }, { 95, 199.1 }, { 90, 204.2 }, { 75, 212.1 }, { 50, 224.7 }, { 25, 254.9 }, { 10, 285.4 } }, avgSize = 24.8, healers = { avg = 5.2, mode = 5, modePct = 45 } })
put("Iron Juggernaut", "3x10", { n = 1000, curve = { { 99, 156.2 }, { 95, 171.5 }, { 90, 179.5 }, { 75, 190.8 }, { 50, 202.6 }, { 25, 215.2 }, { 10, 223.6 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 95 } })
put("Iron Juggernaut", "3x25", { n = 540, curve = { { 99, 191.1 }, { 95, 205.4 }, { 90, 211.7 }, { 75, 223.2 }, { 50, 238.2 }, { 25, 258.4 }, { 10, 283.1 } }, avgSize = 24.8, healers = { avg = 4.9, mode = 5, modePct = 70 } })
put("Iron Juggernaut", "4x10", { n = 1000, curve = { { 99, 130.3 }, { 95, 157.9 }, { 90, 179.4 }, { 75, 218.4 }, { 50, 257.8 }, { 25, 284.7 }, { 10, 310.3 } }, avgSize = 10, healers = { avg = 2.4, mode = 2, modePct = 48 } })
put("Iron Juggernaut", "4x25", { n = 628, curve = { { 99, 136.9 }, { 95, 167.2 }, { 90, 184.6 }, { 75, 213.7 }, { 50, 247 }, { 25, 277.3 }, { 10, 313.3 } }, avgSize = 25, healers = { avg = 4.8, mode = 5, modePct = 38 } })
put("Kor'kron Dark Shaman", "3x10", { n = 1000, curve = { { 99, 84.5 }, { 95, 97.5 }, { 90, 104.7 }, { 75, 119.5 }, { 50, 134.4 }, { 25, 149.6 }, { 10, 162.1 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 95 } })
put("Kor'kron Dark Shaman", "3x25", { n = 525, curve = { { 99, 120 }, { 95, 133.4 }, { 90, 141 }, { 75, 155.2 }, { 50, 180.4 }, { 25, 214.7 }, { 10, 242.6 } }, avgSize = 24.8, healers = { avg = 4.9, mode = 5, modePct = 69 } })
put("Kor'kron Dark Shaman", "4x10", { n = 909, curve = { { 99, 116.2 }, { 95, 140.1 }, { 90, 162.8 }, { 75, 198.9 }, { 50, 264 }, { 25, 331 }, { 10, 383.7 } }, avgSize = 10, healers = { avg = 2.2, mode = 2, modePct = 63 } })
put("Kor'kron Dark Shaman", "4x25", { n = 608, curve = { { 99, 100.2 }, { 95, 147.4 }, { 90, 176.8 }, { 75, 235.4 }, { 50, 278.6 }, { 25, 323.9 }, { 10, 370.4 } }, avgSize = 25, healers = { avg = 4.6, mode = 5, modePct = 45 } })
put("Malkorok", "3x10", { n = 1000, curve = { { 99, 107.3 }, { 95, 118.5 }, { 90, 123.8 }, { 75, 133.6 }, { 50, 143.8 }, { 25, 154.6 }, { 10, 161.6 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 91 } })
put("Malkorok", "3x25", { n = 605, curve = { { 99, 124.3 }, { 95, 131.7 }, { 90, 135.9 }, { 75, 144.8 }, { 50, 157.6 }, { 25, 178 }, { 10, 200.3 } }, avgSize = 24.8, healers = { avg = 4.9, mode = 5, modePct = 68 } })
put("Malkorok", "4x10", { n = 796, curve = { { 99, 139.6 }, { 95, 173.3 }, { 90, 187.6 }, { 75, 205.9 }, { 50, 228.8 }, { 25, 253.1 }, { 10, 271.1 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 86 } })
put("Malkorok", "4x25", { n = 558, curve = { { 99, 144.4 }, { 95, 168.8 }, { 90, 186.4 }, { 75, 208.4 }, { 50, 234 }, { 25, 258.6 }, { 10, 280.3 } }, avgSize = 25, healers = { avg = 4.6, mode = 5, modePct = 39 } })
put("Norushen", "3x10", { n = 1000, curve = { { 99, 202 }, { 95, 213.3 }, { 90, 222.9 }, { 75, 236.3 }, { 50, 251.1 }, { 25, 263.9 }, { 10, 274.6 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 95 } })
put("Norushen", "3x25", { n = 474, curve = { { 99, 206.5 }, { 95, 235.1 }, { 90, 242.9 }, { 75, 256.1 }, { 50, 278.3 }, { 25, 308 }, { 10, 343.3 } }, avgSize = 24.7, healers = { avg = 5, mode = 5, modePct = 75 } })
put("Norushen", "4x10", { n = 1000, curve = { { 99, 188.2 }, { 95, 208.6 }, { 90, 222.3 }, { 75, 246.8 }, { 50, 269.9 }, { 25, 295.7 }, { 10, 314.4 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 94 } })
put("Norushen", "4x25", { n = 659, curve = { { 99, 190.2 }, { 95, 219.4 }, { 90, 234.8 }, { 75, 260.4 }, { 50, 289.4 }, { 25, 327.8 }, { 10, 370.5 } }, avgSize = 24.9, healers = { avg = 4.5, mode = 5, modePct = 52 } })
put("Paragons of the Klaxxi", "3x10", { n = 1000, curve = { { 99, 213.6 }, { 95, 234.1 }, { 90, 245.6 }, { 75, 262.3 }, { 50, 285.6 }, { 25, 309.6 }, { 10, 323.8 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 92 } })
put("Paragons of the Klaxxi", "3x25", { n = 630, curve = { { 99, 231.4 }, { 95, 248.8 }, { 90, 258.1 }, { 75, 277.3 }, { 50, 307.7 }, { 25, 353.2 }, { 10, 406.7 } }, avgSize = 24.7, healers = { avg = 4.7, mode = 5, modePct = 58 } })
put("Paragons of the Klaxxi", "4x10", { n = 373, curve = { { 99, 358.8 }, { 95, 401.4 }, { 90, 436.9 }, { 75, 476.1 }, { 50, 516.5 }, { 25, 575.1 }, { 10, 619.5 } }, avgSize = 10, healers = { avg = 2.1, mode = 2, modePct = 85 } })
put("Paragons of the Klaxxi", "4x25", { n = 307, curve = { { 99, 366.2 }, { 95, 402.8 }, { 90, 463.4 }, { 75, 517.9 }, { 50, 593 }, { 25, 649.9 }, { 10, 690.3 } }, avgSize = 25, healers = { avg = 4.8, mode = 5, modePct = 51 } })
put("Sha of Pride", "3x10", { n = 1000, curve = { { 99, 153.1 }, { 95, 165.8 }, { 90, 174.1 }, { 75, 187.9 }, { 50, 202.7 }, { 25, 214.5 }, { 10, 222.8 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 90 } })
put("Sha of Pride", "3x25", { n = 529, curve = { { 99, 152.6 }, { 95, 167.8 }, { 90, 176 }, { 75, 192.6 }, { 50, 212.4 }, { 25, 236.1 }, { 10, 268.3 } }, avgSize = 24.9, healers = { avg = 4.9, mode = 5, modePct = 73 } })
put("Sha of Pride", "4x10", { n = 1000, curve = { { 99, 161.4 }, { 95, 191.7 }, { 90, 210.3 }, { 75, 236.8 }, { 50, 265.3 }, { 25, 305.7 }, { 10, 329.2 } }, avgSize = 10, healers = { avg = 1.8, mode = 2, modePct = 82 } })
put("Sha of Pride", "4x25", { n = 622, curve = { { 99, 156.8 }, { 95, 187.6 }, { 90, 200.2 }, { 75, 234.9 }, { 50, 264.4 }, { 25, 312.2 }, { 10, 353.8 } }, avgSize = 25, healers = { avg = 4.4, mode = 5, modePct = 46 } })
put("Siegecrafter Blackfuse", "3x10", { n = 1000, curve = { { 99, 81.8 }, { 95, 92.6 }, { 90, 99.8 }, { 75, 112.9 }, { 50, 127.9 }, { 25, 142 }, { 10, 152.2 } }, avgSize = 10, healers = { avg = 1.9, mode = 2, modePct = 85 } })
put("Siegecrafter Blackfuse", "3x25", { n = 629, curve = { { 99, 128.4 }, { 95, 139.5 }, { 90, 147.9 }, { 75, 162.8 }, { 50, 187.6 }, { 25, 213.4 }, { 10, 266.8 } }, avgSize = 24.8, healers = { avg = 4.7, mode = 5, modePct = 56 } })
put("Siegecrafter Blackfuse", "4x10", { n = 576, curve = { { 99, 112.9 }, { 95, 151.5 }, { 90, 169.3 }, { 75, 200.6 }, { 50, 240.1 }, { 25, 277.9 }, { 10, 311.1 } }, avgSize = 10, healers = { avg = 1.8, mode = 2, modePct = 74 } })
put("Siegecrafter Blackfuse", "4x25", { n = 450, curve = { { 99, 160.7 }, { 95, 204.5 }, { 90, 232.2 }, { 75, 278.4 }, { 50, 331 }, { 25, 377.6 }, { 10, 415.4 } }, avgSize = 25, healers = { avg = 4.1, mode = 4, modePct = 44 } })
put("Spoils of Pandaria", "3x10", { n = 1000, curve = { { 99, 214.4 }, { 95, 270.2 }, { 90, 281.9 }, { 75, 301.3 }, { 50, 324.3 }, { 25, 347.1 }, { 10, 363.9 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 99 } })
put("Spoils of Pandaria", "3x25", { n = 610, curve = { { 99, 251.1 }, { 95, 267.7 }, { 90, 275 }, { 75, 296.8 }, { 50, 326.6 }, { 25, 365.2 }, { 10, 414.6 } }, avgSize = 24.7, healers = { avg = 5, mode = 5, modePct = 59 } })
put("Spoils of Pandaria", "4x10", { n = 812, curve = { { 99, 248.6 }, { 95, 354.6 }, { 90, 381.3 }, { 75, 421.8 }, { 50, 464.2 }, { 25, 499.4 }, { 10, 522.2 } }, avgSize = 10, healers = { avg = 2, mode = 2, modePct = 100 } })
put("Spoils of Pandaria", "4x25", { n = 558, curve = { { 99, 236 }, { 95, 270.6 }, { 90, 340.3 }, { 75, 401.9 }, { 50, 449.3 }, { 25, 490.5 }, { 10, 513.8 } }, avgSize = 25, healers = { avg = 4.7, mode = 4, modePct = 45 } })
put("Thok the Bloodthirsty", "3x10", { n = 1000, curve = { { 99, 136.1 }, { 95, 143.8 }, { 90, 150.3 }, { 75, 161.2 }, { 50, 177 }, { 25, 194.8 }, { 10, 208.3 } }, avgSize = 10, healers = { avg = 2.1, mode = 2, modePct = 90 } })
put("Thok the Bloodthirsty", "3x25", { n = 608, curve = { { 99, 168.1 }, { 95, 176.4 }, { 90, 184.4 }, { 75, 202.7 }, { 50, 231.8 }, { 25, 265.6 }, { 10, 320.3 } }, avgSize = 24.8, healers = { avg = 5.2, mode = 5, modePct = 61 } })
put("Thok the Bloodthirsty", "4x10", { n = 758, curve = { { 99, 166.8 }, { 95, 202.6 }, { 90, 222.2 }, { 75, 255.7 }, { 50, 300.9 }, { 25, 361.3 }, { 10, 402.7 } }, avgSize = 10, healers = { avg = 2.4, mode = 2, modePct = 55 } })
put("Thok the Bloodthirsty", "4x25", { n = 527, curve = { { 99, 151.5 }, { 95, 217.7 }, { 90, 238.9 }, { 75, 269.6 }, { 50, 310.4 }, { 25, 364.5 }, { 10, 423.2 } }, avgSize = 25, healers = { avg = 5.2, mode = 5, modePct = 35 } })

TP.Percentiles.ids = TP.Percentiles.ids or {}
TP.Percentiles.ids[51598] = "Fallen Protectors"
TP.Percentiles.ids[51622] = "Galakras"
TP.Percentiles.ids[51623] = "Garrosh Hellscream"
TP.Percentiles.ids[51603] = "General Nazgrim"
TP.Percentiles.ids[51602] = "Immerseus"
TP.Percentiles.ids[51600] = "Iron Juggernaut"
TP.Percentiles.ids[51606] = "Kor'kron Dark Shaman"
TP.Percentiles.ids[51595] = "Malkorok"
TP.Percentiles.ids[51624] = "Norushen"
TP.Percentiles.ids[51593] = "Paragons of the Klaxxi"
TP.Percentiles.ids[51604] = "Sha of Pride"
TP.Percentiles.ids[51601] = "Siegecrafter Blackfuse"
TP.Percentiles.ids[51594] = "Spoils of Pandaria"
TP.Percentiles.ids[51599] = "Thok the Bloodthirsty"
