-- GENERATED by scripts\fetch-killtimes.ps1 - do not edit by hand.
-- Kill-duration quantiles per encounter+bracket from WCL speed
-- rankings (seconds; p99 = fastest). Merged into TP.Percentiles.
local _, TP = ...

TP.Percentiles = TP.Percentiles or {}
TP.Percentiles.encounters = TP.Percentiles.encounters or {}
local E = TP.Percentiles.encounters

local function put(name, bracket, killTime)
	E[name] = E[name] or {}
	E[name][bracket] = E[name][bracket] or {}
	E[name][bracket].killTime = killTime
end

put("Belo'ren, Child of Al'ar", "3", { n = 921, curve = { { 99, 70.1 }, { 95, 87.2 }, { 90, 98.1 }, { 75, 122.8 }, { 50, 136 }, { 25, 180.2 }, { 10, 236.5 } }, avgSize = 14.1, healers = { avg = 2.6, mode = 2, modePct = 49 } })
put("Belo'ren, Child of Al'ar", "4", { n = 1000, curve = { { 99, 82 }, { 95, 89.1 }, { 90, 93.8 }, { 75, 100.8 }, { 50, 109.2 }, { 25, 125.5 }, { 10, 133.8 } }, avgSize = 15.7, healers = { avg = 2.3, mode = 2, modePct = 51 } })
put("Belo'ren, Child of Al'ar", "5", { n = 1000, curve = { { 99, 153.7 }, { 95, 234.8 }, { 90, 247.5 }, { 75, 273.8 }, { 50, 289.4 }, { 25, 297.8 }, { 10, 301.5 } }, avgSize = 20, healers = { avg = 3.3, mode = 3, modePct = 61 } })
put("Chimaerus, the Undreamt God", "3", { n = 950, curve = { { 99, 112.7 }, { 95, 149.9 }, { 90, 159.2 }, { 75, 258.7 }, { 50, 303.2 }, { 25, 332.2 }, { 10, 394.7 } }, avgSize = 14.2, healers = { avg = 2.6, mode = 2, modePct = 52 } })
put("Chimaerus, the Undreamt God", "4", { n = 1000, curve = { { 99, 128 }, { 95, 140.2 }, { 90, 237.3 }, { 75, 252.3 }, { 50, 264.1 }, { 25, 276.7 }, { 10, 286.7 } }, avgSize = 15.3, healers = { avg = 2.6, mode = 2, modePct = 54 } })
put("Chimaerus, the Undreamt God", "5", { n = 1000, curve = { { 99, 123.5 }, { 95, 131.8 }, { 90, 134.8 }, { 75, 140 }, { 50, 144.9 }, { 25, 148.5 }, { 10, 283.9 } }, avgSize = 20, healers = { avg = 2.3, mode = 2, modePct = 79 } })
put("Crown of the Cosmos", "3", { n = 929, curve = { { 99, 228 }, { 95, 250.4 }, { 90, 260.7 }, { 75, 285.1 }, { 50, 316.6 }, { 25, 347.9 }, { 10, 393.4 } }, avgSize = 14.1, healers = { avg = 2.6, mode = 2, modePct = 50 } })
put("Crown of the Cosmos", "4", { n = 1000, curve = { { 99, 338.7 }, { 95, 365.6 }, { 90, 377.2 }, { 75, 400.2 }, { 50, 428 }, { 25, 451.2 }, { 10, 466 } }, avgSize = 13.8, healers = { avg = 2.6, mode = 2, modePct = 51 } })
put("Crown of the Cosmos", "5", { n = 1000, curve = { { 99, 389.4 }, { 95, 409.9 }, { 90, 421.9 }, { 75, 441.1 }, { 50, 461.4 }, { 25, 480.9 }, { 10, 488.4 } }, avgSize = 20, healers = { avg = 3.8, mode = 4, modePct = 81 } })
put("Fallen-King Salhadaar", "3", { n = 999, curve = { { 99, 95.4 }, { 95, 118.2 }, { 90, 129.4 }, { 75, 153.5 }, { 50, 195.5 }, { 25, 238.8 }, { 10, 280 } }, avgSize = 14.5, healers = { avg = 2.5, mode = 2, modePct = 47 } })
put("Fallen-King Salhadaar", "4", { n = 1000, curve = { { 99, 155.6 }, { 95, 179.1 }, { 90, 187.4 }, { 75, 205.7 }, { 50, 227.9 }, { 25, 241.2 }, { 10, 249.7 } }, avgSize = 15.2, healers = { avg = 2.6, mode = 2, modePct = 54 } })
put("Fallen-King Salhadaar", "5", { n = 1000, curve = { { 99, 155.3 }, { 95, 169.2 }, { 90, 178.3 }, { 75, 192.9 }, { 50, 213.9 }, { 25, 235.6 }, { 10, 244.8 } }, avgSize = 20, healers = { avg = 3, mode = 3, modePct = 54 } })
put("Imperator Averzian", "3", { n = 1000, curve = { { 99, 69.3 }, { 95, 89.4 }, { 90, 107.6 }, { 75, 163.8 }, { 50, 208.7 }, { 25, 218 }, { 10, 229.2 } }, avgSize = 14.2, healers = { avg = 2.5, mode = 2, modePct = 47 } })
put("Imperator Averzian", "4", { n = 1000, curve = { { 99, 104.2 }, { 95, 114.7 }, { 90, 124.1 }, { 75, 140.3 }, { 50, 154 }, { 25, 164.9 }, { 10, 169.8 } }, avgSize = 15, healers = { avg = 2.5, mode = 2, modePct = 52 } })
put("Imperator Averzian", "5", { n = 1000, curve = { { 99, 153 }, { 95, 168.8 }, { 90, 175.4 }, { 75, 187.9 }, { 50, 200.6 }, { 25, 209.5 }, { 10, 214.6 } }, avgSize = 20, healers = { avg = 2.7, mode = 3, modePct = 42 } })
put("Lightblinded Vanguard", "3", { n = 976, curve = { { 99, 117.3 }, { 95, 156.8 }, { 90, 167.2 }, { 75, 175.5 }, { 50, 184.6 }, { 25, 198.6 }, { 10, 247.9 } }, avgSize = 14.1, healers = { avg = 2.5, mode = 2, modePct = 47 } })
put("Lightblinded Vanguard", "4", { n = 1000, curve = { { 99, 163.9 }, { 95, 185.2 }, { 90, 192.4 }, { 75, 203.9 }, { 50, 221.6 }, { 25, 248.1 }, { 10, 253.8 } }, avgSize = 15.3, healers = { avg = 2.7, mode = 2, modePct = 45 } })
put("Lightblinded Vanguard", "5", { n = 1000, curve = { { 99, 276.4 }, { 95, 293.7 }, { 90, 306.4 }, { 75, 338.2 }, { 50, 352.1 }, { 25, 387.9 }, { 10, 397.2 } }, avgSize = 20, healers = { avg = 4.5, mode = 4, modePct = 53 } })
put("Midnight Falls", "3", { n = 895, curve = { { 99, 171.2 }, { 95, 233.7 }, { 90, 270.3 }, { 75, 410.7 }, { 50, 436.8 }, { 25, 480 }, { 10, 494.8 } }, avgSize = 14.2, healers = { avg = 2.7, mode = 2, modePct = 45 } })
put("Midnight Falls", "4", { n = 1000, curve = { { 99, 265.3 }, { 95, 288.3 }, { 90, 298.8 }, { 75, 320.9 }, { 50, 342.5 }, { 25, 356.1 }, { 10, 363.5 } }, avgSize = 16.2, healers = { avg = 2.9, mode = 3, modePct = 43 } })
put("Midnight Falls", "5", { n = 1000, curve = { { 99, 483.9 }, { 95, 490.1 }, { 90, 494.1 }, { 75, 500.8 }, { 50, 507.8 }, { 25, 513.1 }, { 10, 517.3 } }, avgSize = 20, healers = { avg = 4, mode = 4, modePct = 97 } })
put("Vaelgor & Ezzorak", "3", { n = 970, curve = { { 99, 119.5 }, { 95, 139.4 }, { 90, 157.9 }, { 75, 191.6 }, { 50, 233.7 }, { 25, 294 }, { 10, 342.2 } }, avgSize = 14.3, healers = { avg = 2.4, mode = 2, modePct = 52 } })
put("Vaelgor & Ezzorak", "4", { n = 1000, curve = { { 99, 232.9 }, { 95, 277.6 }, { 90, 287.2 }, { 75, 305.8 }, { 50, 323.6 }, { 25, 341.5 }, { 10, 352 } }, avgSize = 14.8, healers = { avg = 2.6, mode = 2, modePct = 52 } })
put("Vaelgor & Ezzorak", "5", { n = 1000, curve = { { 99, 235.4 }, { 95, 257.5 }, { 90, 264.2 }, { 75, 282.2 }, { 50, 339.5 }, { 25, 361.3 }, { 10, 372.5 } }, avgSize = 20, healers = { avg = 3.5, mode = 4, modePct = 52 } })
put("Vorasius", "3", { n = 997, curve = { { 99, 109.8 }, { 95, 148.2 }, { 90, 171.5 }, { 75, 258.3 }, { 50, 297.1 }, { 25, 325 }, { 10, 353.1 } }, avgSize = 14, healers = { avg = 2.6, mode = 2, modePct = 46 } })
put("Vorasius", "4", { n = 1000, curve = { { 99, 144.9 }, { 95, 160.4 }, { 90, 167.5 }, { 75, 183.4 }, { 50, 200.5 }, { 25, 220.4 }, { 10, 231 } }, avgSize = 15.1, healers = { avg = 2.5, mode = 2, modePct = 51 } })
put("Vorasius", "5", { n = 1000, curve = { { 99, 167.3 }, { 95, 178.3 }, { 90, 186 }, { 75, 196.8 }, { 50, 211.9 }, { 25, 233.3 }, { 10, 243.7 } }, avgSize = 20, healers = { avg = 2.7, mode = 3, modePct = 44 } })

TP.Percentiles.ids = TP.Percentiles.ids or {}
TP.Percentiles.ids[3182] = "Belo'ren, Child of Al'ar"
TP.Percentiles.ids[3306] = "Chimaerus, the Undreamt God"
TP.Percentiles.ids[3181] = "Crown of the Cosmos"
TP.Percentiles.ids[3179] = "Fallen-King Salhadaar"
TP.Percentiles.ids[3176] = "Imperator Averzian"
TP.Percentiles.ids[3180] = "Lightblinded Vanguard"
TP.Percentiles.ids[3183] = "Midnight Falls"
TP.Percentiles.ids[3178] = "Vaelgor & Ezzorak"
TP.Percentiles.ids[3177] = "Vorasius"
