-- GENERATED by scripts\fetch-killtimes.ps1 - do not edit by hand.
-- Kill-duration quantiles per encounter+bracket from WCL speed
-- rankings (seconds; p99 = fastest). Merged into TP.Percentiles.
local _, TP = ...

TP.Percentiles = TP.Percentiles or {}
TP.Percentiles.encounters = TP.Percentiles.encounters or {}
local E = TP.Percentiles.encounters

local function put(name, bracket, killTime)
	E[name] = E[name] or {}
	E[name][bracket] = E[name][bracket] or {}
	E[name][bracket].killTime = killTime
end

put("Rotmire", "3", { n = 1000, curve = { { 99, 118.2 }, { 95, 131 }, { 90, 135.9 }, { 75, 146.3 }, { 50, 157.4 }, { 25, 168.2 }, { 10, 175 } } })
put("Rotmire", "4", { n = 1000, curve = { { 99, 227.4 }, { 95, 237 }, { 90, 247.5 }, { 75, 262.2 }, { 50, 275.4 }, { 25, 284.8 }, { 10, 289.5 } } })
put("Rotmire", "5", { n = 1000, curve = { { 99, 320.9 }, { 95, 337.9 }, { 90, 345.8 }, { 75, 363 }, { 50, 382 }, { 25, 394.1 }, { 10, 399.8 } } })
