-- GENERATED by scripts\fetch-report-tables.ps1 - do not edit by hand.
-- Per-spec overheal%% quantiles from WCL Healing tables. The engine's
-- overheal adjustment: above p90 = -2, above p75 = -1, below p25 = +1.
-- Generated 2026-07-25 - VS / DR / MQD.
local _, TP = ...

TP.OverhealCurves = TP.OverhealCurves or {}
TP.OverhealCurves[105] = { p25 = 39.1, p75 = 48.4, p90 = 52.5, n = 86 }
TP.OverhealCurves[264] = { p25 = 18.7, p75 = 29.9, p90 = 32.4, n = 49 }
TP.OverhealCurves[270] = { p25 = 27.9, p75 = 37.4, p90 = 42.7, n = 51 }
