-- GENERATED by scripts\fetch-report-tables.ps1 - do not edit by hand.
-- Per-spec overheal%% quantiles from WCL Healing tables. The engine's
-- overheal adjustment: above p90 = -2, above p75 = -1, below p25 = +1.
-- Generated 2026-09-06 - Siege of Orgrimmar.
local _, TP = ...

TP.OverhealCurves = TP.OverhealCurves or {}
TP.OverhealCurves[105] = { p25 = 39.2, p75 = 58.8, p90 = 64.1, n = 134 }
TP.OverhealCurves[264] = { p25 = 30.4, p75 = 51.2, p90 = 57.8, n = 57 }
