-- GENERATED by scripts\fetch-report-tables.ps1 - do not edit by hand.
-- Per-spec overheal%% quantiles from WCL Healing tables. The engine's
-- overheal adjustment: above p90 = -2, above p75 = -1, below p25 = +1.
-- Generated 2026-08-03 - VS / DR / MQD.
local _, TP = ...

TP.OverhealCurves = TP.OverhealCurves or {}
TP.OverhealCurves[65] = { p25 = 28.2, p75 = 36.9, p90 = 43.4, n = 41 }
TP.OverhealCurves[105] = { p25 = 37.9, p75 = 47.7, p90 = 50.7, n = 102 }
TP.OverhealCurves[256] = { p25 = 27.5, p75 = 34.9, p90 = 39.1, n = 52 }
TP.OverhealCurves[257] = { p25 = 33.9, p75 = 43.6, p90 = 50, n = 45 }
TP.OverhealCurves[264] = { p25 = 17.6, p75 = 25.3, p90 = 27.9, n = 110 }
TP.OverhealCurves[270] = { p25 = 25.2, p75 = 35.5, p90 = 39.7, n = 76 }
