-- GENERATED by scripts\fetch-overheal.ps1 - do not edit by hand.
-- Per-spec overheal%% quantiles sampled from WCL report Healing
-- tables (the rankings API has no overheal metric). The engine's
-- overheal adjustment uses these instead of fixed thresholds:
-- above p90 = -2, above p75 = -1, below p25 = +1.
-- Generated 2026-07-21 - Siege of Orgrimmar, 120 tables sampled.
local _, TP = ...

TP.OverhealCurves = TP.OverhealCurves or {}
TP.OverhealCurves[65] = { p25 = 36.6, p75 = 54.9, p90 = 61.9, n = 65 }
TP.OverhealCurves[105] = { p25 = 37.4, p75 = 60.3, p90 = 67.3, n = 72 }
TP.OverhealCurves[256] = { p25 = 27.3, p75 = 48.6, p90 = 55.8, n = 65 }
TP.OverhealCurves[264] = { p25 = 31.3, p75 = 57.5, p90 = 64.5, n = 96 }
TP.OverhealCurves[270] = { p25 = 37.1, p75 = 58.6, p90 = 63.5, n = 48 }
