-- GENERATED by scripts\fetch-report-tables.ps1 - do not edit by hand.
-- Per-spec overheal%% quantiles from WCL Healing tables. The engine's
-- overheal adjustment: above p90 = -2, above p75 = -1, below p25 = +1.
-- Generated 2026-08-06 - Siege of Orgrimmar.
local _, TP = ...

TP.OverhealCurves = TP.OverhealCurves or {}
TP.OverhealCurves[105] = { p25 = 38, p75 = 57, p90 = 62.9, n = 132 }
TP.OverhealCurves[256] = { p25 = 27, p75 = 40.5, p90 = 50.2, n = 40 }
TP.OverhealCurves[264] = { p25 = 31.5, p75 = 53.9, p90 = 60.4, n = 61 }
