-- GENERATED by scripts\fetch-report-tables.ps1 - do not edit by hand.
-- Per-spec overheal%% quantiles from WCL Healing tables. The engine's
-- overheal adjustment: above p90 = -2, above p75 = -1, below p25 = +1.
-- Generated 2026-10-03 - The Venomous Abyss.
local _, TP = ...

TP.OverhealCurves = TP.OverhealCurves or {}
TP.OverhealCurves[65] = { p25 = 26.9, p75 = 37.7, p90 = 45.2, n = 98 }
TP.OverhealCurves[105] = { p25 = 34.8, p75 = 45.6, p90 = 53.3, n = 109 }
TP.OverhealCurves[257] = { p25 = 28.3, p75 = 38.8, p90 = 43.9, n = 120 }
TP.OverhealCurves[264] = { p25 = 14.9, p75 = 25.6, p90 = 32.3, n = 145 }
TP.OverhealCurves[270] = { p25 = 21.6, p75 = 35.6, p90 = 41.9, n = 41 }
TP.OverhealCurves[1468] = { p25 = 28, p75 = 37.9, p90 = 44, n = 49 }
