-- GENERATED by scripts\fetch-percentiles-v2.ps1 - do not edit by hand.
-- MoP SoO 25-man percentile curves (brackets 3x25/4x25). Split from
-- Percentiles_Mists.lua so the monthly CI refresh can crawl each raid
-- size in its own daily window (4 brackets blew the 6h job cap). Both
-- files ADD to TP.Percentiles.encounters at load. This stub is empty
-- until the first mop-pct-25 refresh slice replaces it; until then the
-- 25-man brackets still ship inside Percentiles_Mists.lua.
local _, TP = ...

TP.Percentiles = TP.Percentiles or {}
TP.Percentiles.encounters = TP.Percentiles.encounters or {}
