-- Per-spec active-mitigation UPTIME baselines: { p25, p50, p75 } of the
-- fraction of a fight tanks of this spec hold active mitigation up. The
-- Mitigation metric scores a tank's own uptime as a percentile against its
-- spec's field, WCL-relative like a damage parse (Josh 2026-07-26).
--
-- RETAIL. Regenerated by scripts/fetch-tank-mitigation.ps1 (the CI
-- tank-mit slice) once the retail mit-buff ids in Data/Mitigation.lua are
-- verified; until a spec has real numbers the provisional default applies.
-- MoP baselines live in TankAnchors_Mists.lua. NEVER hand-tune the
-- per-spec entries - quantiles come from data.
local _, TP = ...

TP.TANK_ANCHORS = {
	default = { 30, 55, 75 }, -- provisional, all specs, pre-calibration
	-- [66]  = { p25, p50, p75 },  -- Prot Paladin   (emit from the crawl)
	-- [73]  = { p25, p50, p75 },  -- Prot Warrior
	-- [104] = { p25, p50, p75 },  -- Guardian Druid
	-- [250] = { p25, p50, p75 },  -- Blood DK
	-- [268] = { p25, p50, p75 },  -- Brewmaster
	-- [581] = { p25, p50, p75 },  -- Vengeance DH
}
