-- Per-spec active-mitigation UPTIME baselines: { p25, p50, p75 } of the
-- fraction of a fight tanks of this spec hold active mitigation up,
-- crawled from Warcraft Logs (scripts/fetch-tank-mitigation.ps1). The
-- Tanking metric scores a tank's own uptime as a percentile against its
-- spec's field, so "equally skilled tanks parse similarly" holds the same
-- way damage parses do. WCL-relative, never hand-tuned (Josh 2026-07-26).
-- Regenerated by CI; the provisional default applies to any spec without
-- enough samples yet.
local _, TP = ...

TP.TANK_ANCHORS = {
	default = { 30, 55, 75 }, -- provisional, pre-calibration
	[66] = { 35.9, 58.9, 74.7 }, -- Prot Paladin (n=92)
	[73] = { 17.4, 28.9, 40.9 }, -- Prot Warrior (n=75)
	[104] = { 14.5, 24.3, 39.6 }, -- Guardian Druid (n=57)
	[250] = { 46.4, 56.5, 65.6 }, -- Blood DK (n=105)
	[268] = { 68.4, 84.8, 97.1 }, -- Brewmaster (n=75)
}