-- Per-spec active-mitigation UPTIME baselines: { p25, p50, p75 } of the
-- fraction of a fight tanks of this spec hold active mitigation up,
-- crawled from Warcraft Logs (scripts/fetch-tank-mitigation.ps1). The
-- Tanking metric scores a tank's own uptime as a percentile against its
-- spec's field, so "equally skilled tanks parse similarly" holds the same
-- way damage parses do. WCL-relative, never hand-tuned (Josh 2026-07-26).
-- Regenerated by CI. A spec without enough samples falls back to default,
-- which is itself DERIVED from the crawled specs (median per quantile) so a
-- rare spec is judged against the middle of its peers rather than a guess.
local _, TP = ...

TP.TANK_ANCHORS = {
	default = { 80.1, 90.6, 96.7 }, -- DERIVED: median of the 5 crawled specs
	[66] = { 97.6, 98.6, 99.1 }, -- Prot Paladin (n=48)
	[73] = { 85.6, 92.8, 96.7 }, -- Prot Warrior (n=86)
	[104] = { 19.8, 48.1, 86.5 }, -- Guardian Druid (n=62)
	[250] = { 76.4, 82.2, 91.2 }, -- Blood DK (n=97)
	[581] = { 80.1, 90.6, 98.8 }, -- Vengeance DH (n=40)
}