-- Per-spec active-mitigation UPTIME baselines: { p25, p50, p75 } of the
-- fraction of a fight tanks of this spec hold active mitigation up,
-- crawled from Warcraft Logs (scripts/fetch-tank-mitigation.ps1). The
-- Tanking metric scores a tank's own uptime as a percentile against its
-- spec's field, so "equally skilled tanks parse similarly" holds the same
-- way damage parses do. WCL-relative, never hand-tuned (Josh 2026-07-26).
-- Regenerated by CI. A spec without enough samples falls back to default,
-- which is itself DERIVED from the crawled specs (median per quantile) so a
-- rare spec is judged against the middle of its peers rather than a guess.
local _, TP = ...

TP.TANK_ANCHORS = {
	default = { 32.1, 54.9, 69.4 }, -- DERIVED: median of the 5 crawled specs
	[66] = { 32.1, 54.9, 73.3 }, -- Prot Paladin (n=77)
	[73] = { 12, 28.9, 41.2 }, -- Prot Warrior (n=60)
	[104] = { 5.1, 15.7, 30.2 }, -- Guardian Druid (n=59)
	[250] = { 49.2, 60.1, 69.4 }, -- Blood DK (n=96)
	[268] = { 67.1, 80.1, 96.1 }, -- Brewmaster (n=68)
}