-- Per-spec active-mitigation UPTIME baselines: { p25, p50, p75 } of the
-- fraction of a fight tanks of this spec hold active mitigation up,
-- crawled from Warcraft Logs (scripts/fetch-tank-mitigation.ps1). The
-- Tanking metric scores a tank's own uptime as a percentile against its
-- spec's field, so "equally skilled tanks parse similarly" holds the same
-- way damage parses do. WCL-relative, never hand-tuned (Josh 2026-07-26).
-- Regenerated by CI. A spec without enough samples falls back to default,
-- which is itself DERIVED from the crawled specs (median per quantile) so a
-- rare spec is judged against the middle of its peers rather than a guess.
local _, TP = ...

TP.TANK_ANCHORS = {
	default = { 35.9, 56.1, 63.9 }, -- DERIVED: median of the 5 crawled specs
	[66] = { 35.9, 56.1, 70.5 }, -- Prot Paladin (n=88)
	[73] = { 12.6, 28.3, 38 }, -- Prot Warrior (n=60)
	[104] = { 9.9, 18.4, 33.3 }, -- Guardian Druid (n=50)
	[250] = { 46, 56.1, 63.9 }, -- Blood DK (n=93)
	[268] = { 66.3, 79.8, 96.6 }, -- Brewmaster (n=71)
}