-- Per-spec active-mitigation UPTIME baselines: { p25, p50, p75 } of the
-- fraction of a fight tanks of this spec hold active mitigation up,
-- crawled from Warcraft Logs (scripts/fetch-tank-mitigation.ps1). The
-- Tanking metric scores a tank's own uptime as a percentile against its
-- spec's field, so "equally skilled tanks parse similarly" holds the same
-- way damage parses do. WCL-relative, never hand-tuned (Josh 2026-07-26).
-- Regenerated by CI. A spec without enough samples falls back to default,
-- which is itself DERIVED from the crawled specs (median per quantile) so a
-- rare spec is judged against the middle of its peers rather than a guess.
local _, TP = ...

TP.TANK_ANCHORS = {
	default = { 85.6, 92.7, 98.6 }, -- DERIVED: median of the 6 crawled specs
	[66] = { 97.9, 98.6, 99.1 }, -- Prot Paladin (n=50)
	[73] = { 85.6, 92.7, 96.4 }, -- Prot Warrior (n=82)
	[104] = { 20.1, 51.8, 86.5 }, -- Guardian Druid (n=64)
	[250] = { 76.2, 82.2, 90.6 }, -- Blood DK (n=99)
	[268] = { 99.1, 99.4, 99.7 }, -- Brewmaster (n=61)
	[581] = { 76.6, 89.3, 98.6 }, -- Vengeance DH (n=43)
}