-- GENERATED by scripts\fetch-totals.ps1 - do not edit by hand.
-- True population sizes for curve entries that hit WCL's rankings
-- caps (2000 chars/spec, 1000 kills). The engine rescales a capped
-- curve's sample percentile into the real population: without this,
-- mid-pack players of POPULAR specs read 10-30 points low and the
-- kill-speed field is overestimated ~3x (validated 2026-07-22
-- against report ByCMpAjX9HnYDkQr's official rankPercents).
-- Generated 2026-08-06 - Siege of Orgrimmar.
local _, TP = ...

local E = TP.Percentiles and TP.Percentiles.encounters
if not E then return end
local function put(name, bracket, kills, dps, hps)
	local b = E[name] and E[name][bracket]
	if not b then return end
	if kills and kills > 0 and b.killTime and kills > (b.killTime.n or 0) then
		b.killTime.total = kills
	end
	local function mark(kind, map)
		for sid, m in pairs(map) do
			local e = b[kind] and b[kind][sid]
			if e and m > (e.n or 0) then e.total = m end
		end
	end
	mark("dps", dps or {})
	mark("hps", hps or {})
end

put("Fallen Protectors", "3x10", 1378, { [105] = 2298, [250] = 2390, [255] = 2970, [256] = 2236, [262] = 3192 }, { [105] = 2298, [250] = 2390, [255] = 2970, [256] = 2236, [262] = 3192 })
put("Fallen Protectors", "4x25", nil, { [262] = 2295, [265] = 2081 }, { [262] = 2295, [265] = 2081 })
put("Galakras", "3x10", 1417, { [250] = 2306, [255] = 2883, [262] = 3147, [267] = 2306 }, { [250] = 2306, [255] = 2883, [262] = 3147, [267] = 2306 })
put("Galakras", "4x10", 1001, nil, nil)
put("Galakras", "4x25", nil, { [262] = 2308 }, { [262] = 2308 })
put("Garrosh Hellscream", "3x10", 1338, nil, nil)
put("Garrosh Hellscream", "3x25", nil, { [262] = 2194 }, { [262] = 2194 })
put("General Nazgrim", "3x10", 1332, { [255] = 2536, [262] = 2901 }, { [255] = 2536, [262] = 2901 })
put("General Nazgrim", "4x25", nil, { [262] = 2233 }, { [262] = 2233 })
put("Immerseus", "3x10", 1218, { [105] = 2244, [255] = 2703, [262] = 2808 }, { [105] = 2244, [255] = 2703, [262] = 2808 })
put("Immerseus", "4x10", 1138, nil, nil)
put("Immerseus", "4x25", nil, { [255] = 2082, [262] = 2260, [264] = 2100 }, { [255] = 2082, [262] = 2260, [264] = 2100 })
put("Iron Juggernaut", "3x10", 1475, { [105] = 2317, [250] = 2340, [255] = 2891, [256] = 2261, [262] = 3058, [264] = 2256 }, { [105] = 2317, [250] = 2340, [255] = 2891, [256] = 2261, [262] = 3058, [264] = 2256 })
put("Iron Juggernaut", "3x25", nil, { [262] = 1997 }, { [262] = 1997 })
put("Kor'kron Dark Shaman", "3x10", 1440, { [250] = 2305, [255] = 2635, [262] = 2981 }, { [250] = 2305, [255] = 2635, [262] = 2981 })
put("Malkorok", "3x10", 1504, { [255] = 2686, [262] = 3015 }, { [255] = 2686, [262] = 3015 })
put("Malkorok", "3x25", nil, { [255] = 2029, [262] = 2214 }, { [255] = 2029, [262] = 2214 })
put("Norushen", "3x10", 1304, { [250] = 2262, [255] = 2771, [262] = 2933 }, { [250] = 2262, [255] = 2771, [262] = 2933 })
put("Norushen", "4x10", 1129, nil, nil)
put("Norushen", "4x25", nil, { [262] = 2245 }, { [262] = 2245 })
put("Paragons of the Klaxxi", "3x10", 1451, { [262] = 2674 }, { [262] = 2674 })
put("Paragons of the Klaxxi", "3x25", nil, { [262] = 2306 }, { [262] = 2306 })
put("Sha of Pride", "3x10", 1362, { [250] = 2321, [255] = 2875, [262] = 3188 }, { [250] = 2321, [255] = 2875, [262] = 3188 })
put("Sha of Pride", "3x25", nil, { [262] = 2016 }, { [262] = 2016 })
put("Sha of Pride", "4x10", 1014, nil, nil)
put("Sha of Pride", "4x25", nil, { [262] = 2058 }, { [262] = 2058 })
put("Siegecrafter Blackfuse", "3x10", 1485, { [255] = 2566, [262] = 2840 }, { [255] = 2566, [262] = 2840 })
put("Siegecrafter Blackfuse", "3x25", nil, { [255] = 2010, [262] = 2303 }, { [255] = 2010, [262] = 2303 })
put("Spoils of Pandaria", "3x10", 1498, { [255] = 2605, [262] = 3032 }, { [255] = 2605, [262] = 3032 })
put("Spoils of Pandaria", "3x25", nil, { [255] = 2023, [262] = 2220 }, { [255] = 2023, [262] = 2220 })
put("Thok the Bloodthirsty", "3x10", 1488, { [255] = 2520, [262] = 2754 }, { [255] = 2520, [262] = 2754 })
put("Thok the Bloodthirsty", "3x25", nil, { [262] = 2039 }, { [262] = 2039 })
