-- GENERATED by scripts\fetch-totals.ps1 - do not edit by hand.
-- True population sizes for curve entries that hit WCL's rankings
-- caps (2000 chars/spec, 1000 kills). The engine rescales a capped
-- curve's sample percentile into the real population: without this,
-- mid-pack players of POPULAR specs read 10-30 points low and the
-- kill-speed field is overestimated ~3x (validated 2026-07-22
-- against report ByCMpAjX9HnYDkQr's official rankPercents).
-- Generated 2026-07-22 - Siege of Orgrimmar.
local _, TP = ...

local E = TP.Percentiles and TP.Percentiles.encounters
if not E then return end
local function put(name, bracket, kills, dps, hps)
	local b = E[name] and E[name][bracket]
	if not b then return end
	if kills and kills > 0 and b.killTime and kills > (b.killTime.n or 0) then
		b.killTime.total = kills
	end
	local function mark(kind, map)
		for sid, m in pairs(map) do
			local e = b[kind] and b[kind][sid]
			if e and m > (e.n or 0) then e.total = m end
		end
	end
	mark("dps", dps or {})
	mark("hps", hps or {})
end

put("Fallen Protectors", "3x10", 1350, { [105] = 2088, [250] = 2213, [255] = 2750, [256] = 2064, [262] = 2890 }, { [105] = 2088, [250] = 2213, [255] = 2750, [256] = 2064, [262] = 2890 })
put("Galakras", "3x10", 1387, { [250] = 2137, [255] = 2660, [262] = 2846, [267] = 2114 }, { [250] = 2137, [255] = 2660, [262] = 2846, [267] = 2114 })
put("Garrosh Hellscream", "3x10", 1226, nil, nil)
put("General Nazgrim", "3x10", 1281, { [255] = 2279, [262] = 2582 }, { [255] = 2279, [262] = 2582 })
put("Immerseus", "3x10", 1187, { [105] = 2053, [255] = 2509, [262] = 2539 }, { [105] = 2053, [255] = 2509, [262] = 2539 })
put("Immerseus", "4x10", 1047, nil, nil)
put("Iron Juggernaut", "3x10", 1439, { [105] = 2118, [250] = 2163, [255] = 2654, [256] = 2064, [262] = 2754, [264] = 2054 }, { [105] = 2118, [250] = 2163, [255] = 2654, [256] = 2064, [262] = 2754, [264] = 2054 })
put("Kor'kron Dark Shaman", "3x10", 1393, { [250] = 2099, [255] = 2405, [262] = 2665 }, { [250] = 2099, [255] = 2405, [262] = 2665 })
put("Malkorok", "3x10", 1444, { [255] = 2390, [262] = 2650 }, { [255] = 2390, [262] = 2650 })
put("Malkorok", "3x25", nil, { [262] = 2073 }, { [262] = 2073 })
put("Norushen", "3x10", 1274, { [250] = 2092, [255] = 2557, [262] = 2663 }, { [250] = 2092, [255] = 2557, [262] = 2663 })
put("Paragons of the Klaxxi", "3x10", 1363, { [262] = 2300 }, { [262] = 2300 })
put("Paragons of the Klaxxi", "3x25", nil, { [262] = 2088 }, { [262] = 2088 })
put("Sha of Pride", "3x10", 1330, { [250] = 2142, [255] = 2638, [262] = 2882 }, { [250] = 2142, [255] = 2638, [262] = 2882 })
put("Siegecrafter Blackfuse", "3x10", 1405, { [255] = 2230, [262] = 2468 }, { [255] = 2230, [262] = 2468 })
put("Siegecrafter Blackfuse", "3x25", nil, { [262] = 2094 }, { [262] = 2094 })
put("Spoils of Pandaria", "3x10", 1435, { [255] = 2297, [262] = 2658 }, { [255] = 2297, [262] = 2658 })
put("Spoils of Pandaria", "3x25", nil, { [262] = 2074 }, { [262] = 2074 })
put("Thok the Bloodthirsty", "3x10", 1410, { [255] = 2205, [262] = 2400 }, { [255] = 2205, [262] = 2400 })
