# Installs git hooks that keep Core/Build.lua current, so the dev client always
# reports the commit it is actually running. Safe to re-run.
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$hooks = Join-Path $root ".git\hooks"
if (-not (Test-Path $hooks)) { throw "no .git/hooks at $hooks - not a git checkout?" }

# post-commit and post-checkout both matter: committing changes the hash, and
# switching branches changes it without any commit happening.
$body = @'
#!/bin/sh
# GENERATED by scripts/install-hooks.ps1 - restamps Core/Build.lua
powershell -NoProfile -ExecutionPolicy Bypass -File "$(git rev-parse --show-toplevel)/scripts/stamp-build.ps1" >/dev/null 2>&1 || true
'@
foreach ($h in @("post-commit", "post-checkout", "post-merge")) {
    $p = Join-Path $hooks $h
    [IO.File]::WriteAllText($p, $body.Replace("`r`n", "`n") + "`n", (New-Object Text.UTF8Encoding $false))
    Write-Host "installed $h"
}
& (Join-Path $PSScriptRoot "stamp-build.ps1")
