# Writes Core/Build.lua with the exact source state of THIS working tree, so a
# debug session can be pinned to a commit rather than a version number (Josh
# 2026-07-31: "we know the exact state of the addon during debug sessions").
#
# Core/Build.lua is gitignored and is NOT packaged, so only a client running
# straight from the repo carries it - which is precisely the dev client. A
# CurseForge install has TP.BUILD = nil and its released version instead.
#
# That is why every .toc wraps its Core\Build.lua line in a #@do-not-package@
# block: the packager deletes those lines, so the shipped TOC never asks for a
# file the zip does not contain. Omitting the wrapper shipped a load-time
# error to every user in 2.10.0 and 2.10.1; tests/load.lua now fails on it.
#
# Run it yourself, or install the hooks that keep it current:
#   pwsh scripts/stamp-build.ps1
#   pwsh scripts/install-hooks.ps1     (stamps on every commit and checkout)
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Push-Location $root
try {
    $hash = (git rev-parse --short HEAD).Trim()
    $branch = (git rev-parse --abbrev-ref HEAD).Trim()
    # a tree with uncommitted edits is NOT that commit, and saying so is the
    # whole point - "dirty" is the state most debug sessions are actually in
    $dirty = if ((git status --porcelain)) { "+dirty" } else { "" }
    $when = (git log -1 --format=%cI).Trim()

    $body = @"
-- GENERATED by scripts/stamp-build.ps1 - do not edit, do not commit.
-- Present only in a client running straight from the repo (the dev client);
-- packaged builds have no Build.lua and TP.BUILD stays nil.
local _, TP = ...

TP.BUILD = "$hash$dirty"
TP.BUILD_BRANCH = "$branch"
TP.BUILD_DATE = "$when"
"@
    $path = Join-Path $root "Core\Build.lua"
    [IO.File]::WriteAllText($path, $body.Replace("`r`n", "`n") + "`n", (New-Object Text.UTF8Encoding $false))
    Write-Host "stamped Core/Build.lua = $hash$dirty ($branch)"
}
finally {
    Pop-Location
}
